
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.VBox vbox4;

	private global::Gtk.HBox hbox1;

	private global::Gtk.DrawingArea drawingarea18;

	private global::Gtk.Label lbltitulo;

	private global::Gtk.DrawingArea drawingarea2;

	private global::Gtk.HBox hbox2;

	private global::Gtk.DrawingArea drawingarea17;

	private global::Gtk.DrawingArea drawingarea1;

	private global::Gtk.DrawingArea drawingarea3;

	private global::Gtk.HBox hbox4;

	private global::Gtk.DrawingArea drawingarea16;

	private global::Gtk.Entry entusuario1;

	private global::Gtk.DrawingArea drawingarea4;

	private global::Gtk.HBox hbox5;

	private global::Gtk.DrawingArea drawingarea15;

	private global::Gtk.Entry entcontraseña1;

	private global::Gtk.DrawingArea drawingarea5;

	private global::Gtk.HBox hbox6;

	private global::Gtk.DrawingArea drawingarea14;

	private global::Gtk.Button btniniciar1;

	private global::Gtk.DrawingArea drawingarea6;

	private global::Gtk.HBox hbox7;

	private global::Gtk.DrawingArea drawingarea13;

	private global::Gtk.Button btnsalir;

	private global::Gtk.DrawingArea drawingarea7;

	private global::Gtk.HBox hbox3;

	private global::Gtk.DrawingArea drawingarea10;

	private global::Gtk.DrawingArea drawingarea9;

	private global::Gtk.DrawingArea drawingarea8;

	private global::Gtk.HBox hbox8;

	private global::Gtk.DrawingArea drawingarea12;

	private global::Gtk.Label lblfecha;

	private global::Gtk.Label lblhora;

	private global::Gtk.DrawingArea drawingarea11;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox4 = new global::Gtk.VBox();
		this.vbox4.Name = "vbox4";
		this.vbox4.Spacing = 6;
		// Container child vbox4.Gtk.Box+BoxChild
		this.hbox1 = new global::Gtk.HBox();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.drawingarea18 = new global::Gtk.DrawingArea();
		this.drawingarea18.Name = "drawingarea18";
		this.hbox1.Add(this.drawingarea18);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.drawingarea18]));
		w1.Position = 0;
		// Container child hbox1.Gtk.Box+BoxChild
		this.lbltitulo = new global::Gtk.Label();
		this.lbltitulo.Name = "lbltitulo";
		this.lbltitulo.LabelProp = global::Mono.Unix.Catalog.GetString("Inicio de sesión");
		this.hbox1.Add(this.lbltitulo);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.lbltitulo]));
		w2.Position = 1;
		w2.Expand = false;
		w2.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.drawingarea2 = new global::Gtk.DrawingArea();
		this.drawingarea2.Name = "drawingarea2";
		this.hbox1.Add(this.drawingarea2);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.drawingarea2]));
		w3.Position = 2;
		this.vbox4.Add(this.hbox1);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.hbox1]));
		w4.Position = 0;
		w4.Expand = false;
		w4.Fill = false;
		// Container child vbox4.Gtk.Box+BoxChild
		this.hbox2 = new global::Gtk.HBox();
		this.hbox2.Name = "hbox2";
		this.hbox2.Spacing = 6;
		// Container child hbox2.Gtk.Box+BoxChild
		this.drawingarea17 = new global::Gtk.DrawingArea();
		this.drawingarea17.Name = "drawingarea17";
		this.hbox2.Add(this.drawingarea17);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.drawingarea17]));
		w5.Position = 0;
		// Container child hbox2.Gtk.Box+BoxChild
		this.drawingarea1 = new global::Gtk.DrawingArea();
		this.drawingarea1.Name = "drawingarea1";
		this.hbox2.Add(this.drawingarea1);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.drawingarea1]));
		w6.Position = 1;
		// Container child hbox2.Gtk.Box+BoxChild
		this.drawingarea3 = new global::Gtk.DrawingArea();
		this.drawingarea3.Name = "drawingarea3";
		this.hbox2.Add(this.drawingarea3);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.drawingarea3]));
		w7.Position = 2;
		this.vbox4.Add(this.hbox2);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.hbox2]));
		w8.Position = 1;
		// Container child vbox4.Gtk.Box+BoxChild
		this.hbox4 = new global::Gtk.HBox();
		this.hbox4.Name = "hbox4";
		this.hbox4.Spacing = 6;
		// Container child hbox4.Gtk.Box+BoxChild
		this.drawingarea16 = new global::Gtk.DrawingArea();
		this.drawingarea16.Name = "drawingarea16";
		this.hbox4.Add(this.drawingarea16);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.drawingarea16]));
		w9.Position = 0;
		// Container child hbox4.Gtk.Box+BoxChild
		this.entusuario1 = new global::Gtk.Entry();
		this.entusuario1.CanFocus = true;
		this.entusuario1.Name = "entusuario1";
		this.entusuario1.Text = global::Mono.Unix.Catalog.GetString("Usuario");
		this.entusuario1.IsEditable = true;
		this.entusuario1.InvisibleChar = '●';
		this.hbox4.Add(this.entusuario1);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.entusuario1]));
		w10.Position = 1;
		w10.Expand = false;
		w10.Fill = false;
		// Container child hbox4.Gtk.Box+BoxChild
		this.drawingarea4 = new global::Gtk.DrawingArea();
		this.drawingarea4.Name = "drawingarea4";
		this.hbox4.Add(this.drawingarea4);
		global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.drawingarea4]));
		w11.Position = 2;
		this.vbox4.Add(this.hbox4);
		global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.hbox4]));
		w12.Position = 2;
		w12.Expand = false;
		w12.Fill = false;
		// Container child vbox4.Gtk.Box+BoxChild
		this.hbox5 = new global::Gtk.HBox();
		this.hbox5.Name = "hbox5";
		this.hbox5.Spacing = 6;
		// Container child hbox5.Gtk.Box+BoxChild
		this.drawingarea15 = new global::Gtk.DrawingArea();
		this.drawingarea15.Name = "drawingarea15";
		this.hbox5.Add(this.drawingarea15);
		global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.drawingarea15]));
		w13.Position = 0;
		// Container child hbox5.Gtk.Box+BoxChild
		this.entcontraseña1 = new global::Gtk.Entry();
		this.entcontraseña1.CanFocus = true;
		this.entcontraseña1.Name = "entcontraseña1";
		this.entcontraseña1.Text = global::Mono.Unix.Catalog.GetString("Contraseña");
		this.entcontraseña1.IsEditable = true;
		this.entcontraseña1.Visibility = false;
		this.entcontraseña1.InvisibleChar = '●';
		this.hbox5.Add(this.entcontraseña1);
		global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.entcontraseña1]));
		w14.Position = 1;
		w14.Expand = false;
		w14.Fill = false;
		// Container child hbox5.Gtk.Box+BoxChild
		this.drawingarea5 = new global::Gtk.DrawingArea();
		this.drawingarea5.Name = "drawingarea5";
		this.hbox5.Add(this.drawingarea5);
		global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.drawingarea5]));
		w15.Position = 2;
		this.vbox4.Add(this.hbox5);
		global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.hbox5]));
		w16.Position = 3;
		w16.Expand = false;
		w16.Fill = false;
		// Container child vbox4.Gtk.Box+BoxChild
		this.hbox6 = new global::Gtk.HBox();
		this.hbox6.Name = "hbox6";
		this.hbox6.Spacing = 6;
		// Container child hbox6.Gtk.Box+BoxChild
		this.drawingarea14 = new global::Gtk.DrawingArea();
		this.drawingarea14.Name = "drawingarea14";
		this.hbox6.Add(this.drawingarea14);
		global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.hbox6[this.drawingarea14]));
		w17.Position = 0;
		// Container child hbox6.Gtk.Box+BoxChild
		this.btniniciar1 = new global::Gtk.Button();
		this.btniniciar1.CanFocus = true;
		this.btniniciar1.Name = "btniniciar1";
		this.btniniciar1.UseUnderline = true;
		this.btniniciar1.Label = global::Mono.Unix.Catalog.GetString("Iniciar sesión");
		this.hbox6.Add(this.btniniciar1);
		global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.hbox6[this.btniniciar1]));
		w18.Position = 1;
		w18.Expand = false;
		w18.Fill = false;
		// Container child hbox6.Gtk.Box+BoxChild
		this.drawingarea6 = new global::Gtk.DrawingArea();
		this.drawingarea6.Name = "drawingarea6";
		this.hbox6.Add(this.drawingarea6);
		global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.hbox6[this.drawingarea6]));
		w19.Position = 2;
		this.vbox4.Add(this.hbox6);
		global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.hbox6]));
		w20.Position = 4;
		w20.Expand = false;
		w20.Fill = false;
		// Container child vbox4.Gtk.Box+BoxChild
		this.hbox7 = new global::Gtk.HBox();
		this.hbox7.Name = "hbox7";
		this.hbox7.Spacing = 6;
		// Container child hbox7.Gtk.Box+BoxChild
		this.drawingarea13 = new global::Gtk.DrawingArea();
		this.drawingarea13.Name = "drawingarea13";
		this.hbox7.Add(this.drawingarea13);
		global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.hbox7[this.drawingarea13]));
		w21.Position = 0;
		// Container child hbox7.Gtk.Box+BoxChild
		this.btnsalir = new global::Gtk.Button();
		this.btnsalir.CanFocus = true;
		this.btnsalir.Name = "btnsalir";
		this.btnsalir.UseUnderline = true;
		this.btnsalir.Label = global::Mono.Unix.Catalog.GetString("Salir");
		this.hbox7.Add(this.btnsalir);
		global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.hbox7[this.btnsalir]));
		w22.Position = 1;
		w22.Expand = false;
		w22.Fill = false;
		// Container child hbox7.Gtk.Box+BoxChild
		this.drawingarea7 = new global::Gtk.DrawingArea();
		this.drawingarea7.Name = "drawingarea7";
		this.hbox7.Add(this.drawingarea7);
		global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.hbox7[this.drawingarea7]));
		w23.Position = 2;
		this.vbox4.Add(this.hbox7);
		global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.hbox7]));
		w24.Position = 5;
		w24.Expand = false;
		w24.Fill = false;
		// Container child vbox4.Gtk.Box+BoxChild
		this.hbox3 = new global::Gtk.HBox();
		this.hbox3.Name = "hbox3";
		this.hbox3.Spacing = 6;
		// Container child hbox3.Gtk.Box+BoxChild
		this.drawingarea10 = new global::Gtk.DrawingArea();
		this.drawingarea10.Name = "drawingarea10";
		this.hbox3.Add(this.drawingarea10);
		global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.drawingarea10]));
		w25.Position = 0;
		// Container child hbox3.Gtk.Box+BoxChild
		this.drawingarea9 = new global::Gtk.DrawingArea();
		this.drawingarea9.Name = "drawingarea9";
		this.hbox3.Add(this.drawingarea9);
		global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.drawingarea9]));
		w26.Position = 1;
		// Container child hbox3.Gtk.Box+BoxChild
		this.drawingarea8 = new global::Gtk.DrawingArea();
		this.drawingarea8.Name = "drawingarea8";
		this.hbox3.Add(this.drawingarea8);
		global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.drawingarea8]));
		w27.Position = 2;
		this.vbox4.Add(this.hbox3);
		global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.hbox3]));
		w28.Position = 6;
		// Container child vbox4.Gtk.Box+BoxChild
		this.hbox8 = new global::Gtk.HBox();
		this.hbox8.Name = "hbox8";
		this.hbox8.Spacing = 6;
		// Container child hbox8.Gtk.Box+BoxChild
		this.drawingarea12 = new global::Gtk.DrawingArea();
		this.drawingarea12.Name = "drawingarea12";
		this.hbox8.Add(this.drawingarea12);
		global::Gtk.Box.BoxChild w29 = ((global::Gtk.Box.BoxChild)(this.hbox8[this.drawingarea12]));
		w29.Position = 0;
		// Container child hbox8.Gtk.Box+BoxChild
		this.lblfecha = new global::Gtk.Label();
		this.lblfecha.Name = "lblfecha";
		this.hbox8.Add(this.lblfecha);
		global::Gtk.Box.BoxChild w30 = ((global::Gtk.Box.BoxChild)(this.hbox8[this.lblfecha]));
		w30.Position = 1;
		// Container child hbox8.Gtk.Box+BoxChild
		this.lblhora = new global::Gtk.Label();
		this.lblhora.Name = "lblhora";
		this.hbox8.Add(this.lblhora);
		global::Gtk.Box.BoxChild w31 = ((global::Gtk.Box.BoxChild)(this.hbox8[this.lblhora]));
		w31.Position = 2;
		// Container child hbox8.Gtk.Box+BoxChild
		this.drawingarea11 = new global::Gtk.DrawingArea();
		this.drawingarea11.Name = "drawingarea11";
		this.hbox8.Add(this.drawingarea11);
		global::Gtk.Box.BoxChild w32 = ((global::Gtk.Box.BoxChild)(this.hbox8[this.drawingarea11]));
		w32.Position = 3;
		this.vbox4.Add(this.hbox8);
		global::Gtk.Box.BoxChild w33 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.hbox8]));
		w33.Position = 7;
		w33.Expand = false;
		w33.Fill = false;
		this.Add(this.vbox4);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 400;
		this.DefaultHeight = 300;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.entusuario1.Changed += new global::System.EventHandler(this.OnEntusuario1Changed);
		this.entcontraseña1.Changed += new global::System.EventHandler(this.OnEntcontraseña1Changed);
		this.btniniciar1.Clicked += new global::System.EventHandler(this.OnBtniniciar1Clicked);
	}
}
