
// This file has been generated by the GUI designer. Do not modify.
namespace ProyectoDamageDefinitivo
{
	public partial class ActualizarEstudiante
	{
		private global::Gtk.HBox hbox1;

		private global::Gtk.VBox vbox1;

		private global::Gtk.HBox hbox5;

		private global::Gtk.DrawingArea drawingarea29;

		private global::Gtk.HBox hbox4;

		private global::Gtk.DrawingArea drawingarea28;

		private global::Gtk.DrawingArea drawingarea27;

		private global::Gtk.HBox hbox6;

		private global::Gtk.DrawingArea drawingarea25;

		private global::Gtk.DrawingArea drawingarea24;

		private global::Gtk.VBox vbox2;

		private global::Gtk.Label lblarchest;

		private global::Gtk.HBox hbox13;

		private global::Gtk.Label lblcedest;

		private global::Gtk.Entry entcedest;

		private global::Gtk.HBox hbox14;

		private global::Gtk.Label lblnombest;

		private global::Gtk.Entry entnombest;

		private global::Gtk.HBox hbox15;

		private global::Gtk.Label lblapellido;

		private global::Gtk.Entry entapest;

		private global::Gtk.HBox hbox7;

		private global::Gtk.Label lbledadest;

		private global::Gtk.Entry entedadest;

		private global::Gtk.HBox hbox8;

		private global::Gtk.Label lbltlfest;

		private global::Gtk.HBox hbox16;

		private global::Gtk.ComboBox combotlfest;

		private global::Gtk.Entry enttlfest;

		private global::Gtk.HBox hbox9;

		private global::Gtk.VBox vbox5;

		private global::Gtk.Label lbldireccionest;

		private global::Gtk.DrawingArea drawingarea26;

		private global::Gtk.VBox vbox4;

		private global::Gtk.Entry entdireccionest;

		private global::Gtk.Button btnactualizarest;

		private global::Gtk.VBox vbox3;

		private global::Gtk.HBox hbox10;

		private global::Gtk.DrawingArea drawingarea19;

		private global::Gtk.HBox hbox11;

		private global::Gtk.DrawingArea drawingarea21;

		private global::Gtk.DrawingArea drawingarea20;

		private global::Gtk.HBox hbox12;

		private global::Gtk.DrawingArea drawingarea23;

		private global::Gtk.DrawingArea drawingarea22;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget ProyectoDamageDefinitivo.ActualizarEstudiante
			this.Name = "ProyectoDamageDefinitivo.ActualizarEstudiante";
			this.Title = global::Mono.Unix.Catalog.GetString("ActualizarEstudiante");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child ProyectoDamageDefinitivo.ActualizarEstudiante.Gtk.Container+ContainerChild
			this.hbox1 = new global::Gtk.HBox();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.vbox1 = new global::Gtk.VBox();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox5 = new global::Gtk.HBox();
			this.hbox5.Name = "hbox5";
			this.hbox5.Spacing = 6;
			// Container child hbox5.Gtk.Box+BoxChild
			this.drawingarea29 = new global::Gtk.DrawingArea();
			this.drawingarea29.Name = "drawingarea29";
			this.hbox5.Add(this.drawingarea29);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.drawingarea29]));
			w1.Position = 0;
			this.vbox1.Add(this.hbox5);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox5]));
			w2.Position = 0;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox4 = new global::Gtk.HBox();
			this.hbox4.Name = "hbox4";
			this.hbox4.Spacing = 6;
			// Container child hbox4.Gtk.Box+BoxChild
			this.drawingarea28 = new global::Gtk.DrawingArea();
			this.drawingarea28.Name = "drawingarea28";
			this.hbox4.Add(this.drawingarea28);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.drawingarea28]));
			w3.Position = 0;
			// Container child hbox4.Gtk.Box+BoxChild
			this.drawingarea27 = new global::Gtk.DrawingArea();
			this.drawingarea27.Name = "drawingarea27";
			this.hbox4.Add(this.drawingarea27);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.drawingarea27]));
			w4.Position = 1;
			this.vbox1.Add(this.hbox4);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox4]));
			w5.Position = 1;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox6 = new global::Gtk.HBox();
			this.hbox6.Name = "hbox6";
			this.hbox6.Spacing = 6;
			// Container child hbox6.Gtk.Box+BoxChild
			this.drawingarea25 = new global::Gtk.DrawingArea();
			this.drawingarea25.Name = "drawingarea25";
			this.hbox6.Add(this.drawingarea25);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox6[this.drawingarea25]));
			w6.Position = 0;
			// Container child hbox6.Gtk.Box+BoxChild
			this.drawingarea24 = new global::Gtk.DrawingArea();
			this.drawingarea24.Name = "drawingarea24";
			this.hbox6.Add(this.drawingarea24);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox6[this.drawingarea24]));
			w7.Position = 1;
			this.vbox1.Add(this.hbox6);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox6]));
			w8.Position = 2;
			this.hbox1.Add(this.vbox1);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.vbox1]));
			w9.Position = 0;
			// Container child hbox1.Gtk.Box+BoxChild
			this.vbox2 = new global::Gtk.VBox();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.lblarchest = new global::Gtk.Label();
			this.lblarchest.Name = "lblarchest";
			this.lblarchest.LabelProp = global::Mono.Unix.Catalog.GetString("Archivo Estudiantes");
			this.vbox2.Add(this.lblarchest);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.lblarchest]));
			w10.Position = 0;
			w10.Expand = false;
			w10.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox13 = new global::Gtk.HBox();
			this.hbox13.Name = "hbox13";
			this.hbox13.Spacing = 6;
			// Container child hbox13.Gtk.Box+BoxChild
			this.lblcedest = new global::Gtk.Label();
			this.lblcedest.Name = "lblcedest";
			this.lblcedest.LabelProp = global::Mono.Unix.Catalog.GetString("Cedula");
			this.hbox13.Add(this.lblcedest);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox13[this.lblcedest]));
			w11.Position = 0;
			w11.Expand = false;
			w11.Fill = false;
			// Container child hbox13.Gtk.Box+BoxChild
			this.entcedest = new global::Gtk.Entry();
			this.entcedest.CanFocus = true;
			this.entcedest.Name = "entcedest";
			this.entcedest.IsEditable = true;
			this.entcedest.InvisibleChar = '●';
			this.hbox13.Add(this.entcedest);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox13[this.entcedest]));
			w12.Position = 1;
			this.vbox2.Add(this.hbox13);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.hbox13]));
			w13.Position = 1;
			w13.Expand = false;
			w13.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox14 = new global::Gtk.HBox();
			this.hbox14.Name = "hbox14";
			this.hbox14.Spacing = 6;
			// Container child hbox14.Gtk.Box+BoxChild
			this.lblnombest = new global::Gtk.Label();
			this.lblnombest.Name = "lblnombest";
			this.lblnombest.LabelProp = global::Mono.Unix.Catalog.GetString("Nombre");
			this.hbox14.Add(this.lblnombest);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hbox14[this.lblnombest]));
			w14.Position = 0;
			w14.Expand = false;
			w14.Fill = false;
			// Container child hbox14.Gtk.Box+BoxChild
			this.entnombest = new global::Gtk.Entry();
			this.entnombest.CanFocus = true;
			this.entnombest.Name = "entnombest";
			this.entnombest.IsEditable = true;
			this.entnombest.InvisibleChar = '●';
			this.hbox14.Add(this.entnombest);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.hbox14[this.entnombest]));
			w15.Position = 1;
			this.vbox2.Add(this.hbox14);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.hbox14]));
			w16.Position = 2;
			w16.Expand = false;
			w16.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox15 = new global::Gtk.HBox();
			this.hbox15.Name = "hbox15";
			this.hbox15.Spacing = 6;
			// Container child hbox15.Gtk.Box+BoxChild
			this.lblapellido = new global::Gtk.Label();
			this.lblapellido.Name = "lblapellido";
			this.lblapellido.LabelProp = global::Mono.Unix.Catalog.GetString("Apellido");
			this.hbox15.Add(this.lblapellido);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.hbox15[this.lblapellido]));
			w17.Position = 0;
			w17.Expand = false;
			w17.Fill = false;
			// Container child hbox15.Gtk.Box+BoxChild
			this.entapest = new global::Gtk.Entry();
			this.entapest.CanFocus = true;
			this.entapest.Name = "entapest";
			this.entapest.IsEditable = true;
			this.entapest.InvisibleChar = '●';
			this.hbox15.Add(this.entapest);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.hbox15[this.entapest]));
			w18.Position = 1;
			this.vbox2.Add(this.hbox15);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.hbox15]));
			w19.Position = 3;
			w19.Expand = false;
			w19.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox7 = new global::Gtk.HBox();
			this.hbox7.Name = "hbox7";
			this.hbox7.Spacing = 6;
			// Container child hbox7.Gtk.Box+BoxChild
			this.lbledadest = new global::Gtk.Label();
			this.lbledadest.Name = "lbledadest";
			this.lbledadest.LabelProp = global::Mono.Unix.Catalog.GetString("Edad");
			this.hbox7.Add(this.lbledadest);
			global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.hbox7[this.lbledadest]));
			w20.Position = 0;
			w20.Expand = false;
			w20.Fill = false;
			// Container child hbox7.Gtk.Box+BoxChild
			this.entedadest = new global::Gtk.Entry();
			this.entedadest.CanFocus = true;
			this.entedadest.Name = "entedadest";
			this.entedadest.IsEditable = true;
			this.entedadest.InvisibleChar = '●';
			this.hbox7.Add(this.entedadest);
			global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.hbox7[this.entedadest]));
			w21.Position = 1;
			this.vbox2.Add(this.hbox7);
			global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.hbox7]));
			w22.Position = 4;
			w22.Expand = false;
			w22.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox8 = new global::Gtk.HBox();
			this.hbox8.Name = "hbox8";
			this.hbox8.Spacing = 6;
			// Container child hbox8.Gtk.Box+BoxChild
			this.lbltlfest = new global::Gtk.Label();
			this.lbltlfest.Name = "lbltlfest";
			this.lbltlfest.LabelProp = global::Mono.Unix.Catalog.GetString("Teléfono");
			this.hbox8.Add(this.lbltlfest);
			global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.hbox8[this.lbltlfest]));
			w23.Position = 0;
			w23.Expand = false;
			w23.Fill = false;
			// Container child hbox8.Gtk.Box+BoxChild
			this.hbox16 = new global::Gtk.HBox();
			this.hbox16.Name = "hbox16";
			this.hbox16.Spacing = 6;
			// Container child hbox16.Gtk.Box+BoxChild
			this.combotlfest = global::Gtk.ComboBox.NewText();
			this.combotlfest.AppendText(global::Mono.Unix.Catalog.GetString("0424"));
			this.combotlfest.AppendText(global::Mono.Unix.Catalog.GetString("0414"));
			this.combotlfest.AppendText(global::Mono.Unix.Catalog.GetString("0426"));
			this.combotlfest.AppendText(global::Mono.Unix.Catalog.GetString("0416"));
			this.combotlfest.AppendText(global::Mono.Unix.Catalog.GetString("0412"));
			this.combotlfest.AppendText(global::Mono.Unix.Catalog.GetString("0251"));
			this.combotlfest.Name = "combotlfest";
			this.combotlfest.Active = 0;
			this.hbox16.Add(this.combotlfest);
			global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.hbox16[this.combotlfest]));
			w24.Position = 0;
			w24.Expand = false;
			w24.Fill = false;
			// Container child hbox16.Gtk.Box+BoxChild
			this.enttlfest = new global::Gtk.Entry();
			this.enttlfest.CanFocus = true;
			this.enttlfest.Name = "enttlfest";
			this.enttlfest.IsEditable = true;
			this.enttlfest.InvisibleChar = '●';
			this.hbox16.Add(this.enttlfest);
			global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.hbox16[this.enttlfest]));
			w25.Position = 1;
			this.hbox8.Add(this.hbox16);
			global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.hbox8[this.hbox16]));
			w26.Position = 1;
			this.vbox2.Add(this.hbox8);
			global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.hbox8]));
			w27.Position = 5;
			w27.Expand = false;
			w27.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox9 = new global::Gtk.HBox();
			this.hbox9.Name = "hbox9";
			this.hbox9.Spacing = 6;
			// Container child hbox9.Gtk.Box+BoxChild
			this.vbox5 = new global::Gtk.VBox();
			this.vbox5.Name = "vbox5";
			this.vbox5.Spacing = 6;
			// Container child vbox5.Gtk.Box+BoxChild
			this.lbldireccionest = new global::Gtk.Label();
			this.lbldireccionest.Name = "lbldireccionest";
			this.lbldireccionest.LabelProp = global::Mono.Unix.Catalog.GetString("Direccion");
			this.vbox5.Add(this.lbldireccionest);
			global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.lbldireccionest]));
			w28.Position = 0;
			w28.Expand = false;
			w28.Fill = false;
			// Container child vbox5.Gtk.Box+BoxChild
			this.drawingarea26 = new global::Gtk.DrawingArea();
			this.drawingarea26.Name = "drawingarea26";
			this.vbox5.Add(this.drawingarea26);
			global::Gtk.Box.BoxChild w29 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.drawingarea26]));
			w29.Position = 1;
			this.hbox9.Add(this.vbox5);
			global::Gtk.Box.BoxChild w30 = ((global::Gtk.Box.BoxChild)(this.hbox9[this.vbox5]));
			w30.Position = 0;
			w30.Expand = false;
			w30.Fill = false;
			// Container child hbox9.Gtk.Box+BoxChild
			this.vbox4 = new global::Gtk.VBox();
			this.vbox4.Name = "vbox4";
			this.vbox4.Spacing = 6;
			// Container child vbox4.Gtk.Box+BoxChild
			this.entdireccionest = new global::Gtk.Entry();
			this.entdireccionest.CanFocus = true;
			this.entdireccionest.Name = "entdireccionest";
			this.entdireccionest.IsEditable = true;
			this.entdireccionest.InvisibleChar = '●';
			this.vbox4.Add(this.entdireccionest);
			global::Gtk.Box.BoxChild w31 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.entdireccionest]));
			w31.Position = 0;
			w31.Expand = false;
			w31.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.btnactualizarest = new global::Gtk.Button();
			this.btnactualizarest.CanFocus = true;
			this.btnactualizarest.Name = "btnactualizarest";
			this.btnactualizarest.UseUnderline = true;
			this.btnactualizarest.Label = global::Mono.Unix.Catalog.GetString("Actualizar");
			this.vbox4.Add(this.btnactualizarest);
			global::Gtk.Box.BoxChild w32 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.btnactualizarest]));
			w32.Position = 1;
			w32.Expand = false;
			w32.Fill = false;
			this.hbox9.Add(this.vbox4);
			global::Gtk.Box.BoxChild w33 = ((global::Gtk.Box.BoxChild)(this.hbox9[this.vbox4]));
			w33.Position = 1;
			w33.Expand = false;
			w33.Fill = false;
			this.vbox2.Add(this.hbox9);
			global::Gtk.Box.BoxChild w34 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.hbox9]));
			w34.Position = 6;
			w34.Expand = false;
			w34.Fill = false;
			this.hbox1.Add(this.vbox2);
			global::Gtk.Box.BoxChild w35 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.vbox2]));
			w35.Position = 1;
			w35.Expand = false;
			w35.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.vbox3 = new global::Gtk.VBox();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hbox10 = new global::Gtk.HBox();
			this.hbox10.Name = "hbox10";
			this.hbox10.Spacing = 6;
			// Container child hbox10.Gtk.Box+BoxChild
			this.drawingarea19 = new global::Gtk.DrawingArea();
			this.drawingarea19.Name = "drawingarea19";
			this.hbox10.Add(this.drawingarea19);
			global::Gtk.Box.BoxChild w36 = ((global::Gtk.Box.BoxChild)(this.hbox10[this.drawingarea19]));
			w36.Position = 0;
			this.vbox3.Add(this.hbox10);
			global::Gtk.Box.BoxChild w37 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.hbox10]));
			w37.Position = 0;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hbox11 = new global::Gtk.HBox();
			this.hbox11.Name = "hbox11";
			this.hbox11.Spacing = 6;
			// Container child hbox11.Gtk.Box+BoxChild
			this.drawingarea21 = new global::Gtk.DrawingArea();
			this.drawingarea21.Name = "drawingarea21";
			this.hbox11.Add(this.drawingarea21);
			global::Gtk.Box.BoxChild w38 = ((global::Gtk.Box.BoxChild)(this.hbox11[this.drawingarea21]));
			w38.Position = 0;
			// Container child hbox11.Gtk.Box+BoxChild
			this.drawingarea20 = new global::Gtk.DrawingArea();
			this.drawingarea20.Name = "drawingarea20";
			this.hbox11.Add(this.drawingarea20);
			global::Gtk.Box.BoxChild w39 = ((global::Gtk.Box.BoxChild)(this.hbox11[this.drawingarea20]));
			w39.Position = 1;
			this.vbox3.Add(this.hbox11);
			global::Gtk.Box.BoxChild w40 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.hbox11]));
			w40.Position = 1;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hbox12 = new global::Gtk.HBox();
			this.hbox12.Name = "hbox12";
			this.hbox12.Spacing = 6;
			// Container child hbox12.Gtk.Box+BoxChild
			this.drawingarea23 = new global::Gtk.DrawingArea();
			this.drawingarea23.Name = "drawingarea23";
			this.hbox12.Add(this.drawingarea23);
			global::Gtk.Box.BoxChild w41 = ((global::Gtk.Box.BoxChild)(this.hbox12[this.drawingarea23]));
			w41.Position = 0;
			// Container child hbox12.Gtk.Box+BoxChild
			this.drawingarea22 = new global::Gtk.DrawingArea();
			this.drawingarea22.Name = "drawingarea22";
			this.hbox12.Add(this.drawingarea22);
			global::Gtk.Box.BoxChild w42 = ((global::Gtk.Box.BoxChild)(this.hbox12[this.drawingarea22]));
			w42.Position = 1;
			this.vbox3.Add(this.hbox12);
			global::Gtk.Box.BoxChild w43 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.hbox12]));
			w43.Position = 2;
			this.hbox1.Add(this.vbox3);
			global::Gtk.Box.BoxChild w44 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.vbox3]));
			w44.Position = 2;
			this.Add(this.hbox1);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show();
		}
	}
}
