
// This file has been generated by the GUI designer. Do not modify.
namespace ProyectoDamageDefinitivo
{
	public partial class Validaciones
	{
		private global::Gtk.VBox vbox5;

		private global::Gtk.HBox hbox9;

		private global::Gtk.Label lbloperaciones;

		private global::Gtk.HBox hbox10;

		private global::Gtk.Button btnactualizar;

		private global::Gtk.HBox hbox14;

		private global::Gtk.Button btnreportes;

		private global::Gtk.HBox hbox11;

		private global::Gtk.VBox vbox6;

		private global::Gtk.VBox vbox7;

		private global::Gtk.Button btnsalir2;

		private global::Gtk.HBox hbox15;

		private global::Gtk.Label lblfecha;

		private global::Gtk.Label lblhora;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget ProyectoDamageDefinitivo.Validaciones
			this.Name = "ProyectoDamageDefinitivo.Validaciones";
			this.Title = global::Mono.Unix.Catalog.GetString("Validaciones");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child ProyectoDamageDefinitivo.Validaciones.Gtk.Container+ContainerChild
			this.vbox5 = new global::Gtk.VBox();
			this.vbox5.Name = "vbox5";
			this.vbox5.Spacing = 6;
			// Container child vbox5.Gtk.Box+BoxChild
			this.hbox9 = new global::Gtk.HBox();
			this.hbox9.Name = "hbox9";
			this.hbox9.Spacing = 6;
			// Container child hbox9.Gtk.Box+BoxChild
			this.lbloperaciones = new global::Gtk.Label();
			this.lbloperaciones.Name = "lbloperaciones";
			this.lbloperaciones.LabelProp = global::Mono.Unix.Catalog.GetString("Operaciones a realizar");
			this.hbox9.Add(this.lbloperaciones);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox9[this.lbloperaciones]));
			w1.Position = 1;
			w1.Expand = false;
			w1.Fill = false;
			this.vbox5.Add(this.hbox9);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.hbox9]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox5.Gtk.Box+BoxChild
			this.hbox10 = new global::Gtk.HBox();
			this.hbox10.Name = "hbox10";
			this.hbox10.Spacing = 6;
			// Container child hbox10.Gtk.Box+BoxChild
			this.btnactualizar = new global::Gtk.Button();
			this.btnactualizar.CanFocus = true;
			this.btnactualizar.Name = "btnactualizar";
			this.btnactualizar.UseUnderline = true;
			this.btnactualizar.Label = global::Mono.Unix.Catalog.GetString("Actualización");
			this.hbox10.Add(this.btnactualizar);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox10[this.btnactualizar]));
			w3.Position = 1;
			w3.Expand = false;
			w3.Fill = false;
			this.vbox5.Add(this.hbox10);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.hbox10]));
			w4.Position = 1;
			w4.Expand = false;
			w4.Fill = false;
			// Container child vbox5.Gtk.Box+BoxChild
			this.hbox14 = new global::Gtk.HBox();
			this.hbox14.Name = "hbox14";
			this.hbox14.Spacing = 6;
			// Container child hbox14.Gtk.Box+BoxChild
			this.btnreportes = new global::Gtk.Button();
			this.btnreportes.CanFocus = true;
			this.btnreportes.Name = "btnreportes";
			this.btnreportes.UseUnderline = true;
			this.btnreportes.Label = global::Mono.Unix.Catalog.GetString("Reportes");
			this.hbox14.Add(this.btnreportes);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox14[this.btnreportes]));
			w5.Position = 1;
			w5.Expand = false;
			w5.Fill = false;
			this.vbox5.Add(this.hbox14);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.hbox14]));
			w6.Position = 2;
			w6.Expand = false;
			w6.Fill = false;
			// Container child vbox5.Gtk.Box+BoxChild
			this.hbox11 = new global::Gtk.HBox();
			this.hbox11.Name = "hbox11";
			this.hbox11.Spacing = 6;
			// Container child hbox11.Gtk.Box+BoxChild
			this.vbox6 = new global::Gtk.VBox();
			this.vbox6.Name = "vbox6";
			this.vbox6.Spacing = 6;
			this.hbox11.Add(this.vbox6);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox11[this.vbox6]));
			w7.Position = 0;
			// Container child hbox11.Gtk.Box+BoxChild
			this.vbox7 = new global::Gtk.VBox();
			this.vbox7.Name = "vbox7";
			this.vbox7.Spacing = 6;
			// Container child vbox7.Gtk.Box+BoxChild
			this.btnsalir2 = new global::Gtk.Button();
			this.btnsalir2.CanFocus = true;
			this.btnsalir2.Name = "btnsalir2";
			this.btnsalir2.UseUnderline = true;
			this.btnsalir2.Label = global::Mono.Unix.Catalog.GetString("Salir");
			this.vbox7.Add(this.btnsalir2);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox7[this.btnsalir2]));
			w8.Position = 0;
			w8.Expand = false;
			w8.Fill = false;
			// Container child vbox7.Gtk.Box+BoxChild
			this.hbox15 = new global::Gtk.HBox();
			this.hbox15.Name = "hbox15";
			this.hbox15.Spacing = 6;
			// Container child hbox15.Gtk.Box+BoxChild
			this.lblfecha = new global::Gtk.Label();
			this.lblfecha.Name = "lblfecha";
			this.hbox15.Add(this.lblfecha);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox15[this.lblfecha]));
			w9.Position = 0;
			w9.Expand = false;
			w9.Fill = false;
			// Container child hbox15.Gtk.Box+BoxChild
			this.lblhora = new global::Gtk.Label();
			this.lblhora.Name = "lblhora";
			this.lblhora.LabelProp = global::Mono.Unix.Catalog.GetString("label7");
			this.hbox15.Add(this.lblhora);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox15[this.lblhora]));
			w10.Position = 1;
			w10.Expand = false;
			w10.Fill = false;
			this.vbox7.Add(this.hbox15);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox7[this.hbox15]));
			w11.Position = 1;
			w11.Expand = false;
			w11.Fill = false;
			this.hbox11.Add(this.vbox7);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox11[this.vbox7]));
			w12.Position = 1;
			w12.Expand = false;
			w12.Fill = false;
			this.vbox5.Add(this.hbox11);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.hbox11]));
			w13.Position = 3;
			w13.Expand = false;
			w13.Fill = false;
			this.Add(this.vbox5);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show();
			this.btnactualizar.Clicked += new global::System.EventHandler(this.OnBtnactualizarClicked);
		}
	}
}
