
// This file has been generated by the GUI designer. Do not modify.
namespace ProyectoDamageDefinitivo
{
	public partial class ActualizarInstructor
	{
		private global::Gtk.VBox vbox9;

		private global::Gtk.HBox hbox21;

		private global::Gtk.DrawingArea drawingarea18;

		private global::Gtk.Label lblactualizarinstructor;

		private global::Gtk.DrawingArea drawingarea1;

		private global::Gtk.HBox hbox24;

		private global::Gtk.VBox vbox10;

		private global::Gtk.HBox hbox26;

		private global::Gtk.DrawingArea drawingarea17;

		private global::Gtk.DrawingArea drawingarea16;

		private global::Gtk.VBox vbox13;

		private global::Gtk.HBox hbox27;

		private global::Gtk.Label lblcedins;

		private global::Gtk.Entry entcedins;

		private global::Gtk.HBox hbox29;

		private global::Gtk.Label lblnomins;

		private global::Gtk.Entry entnomins;

		private global::Gtk.VBox vbox18;

		private global::Gtk.HBox hbox28;

		private global::Gtk.DrawingArea drawingarea2;

		private global::Gtk.DrawingArea drawingarea3;

		private global::Gtk.HBox hbox25;

		private global::Gtk.VBox vbox11;

		private global::Gtk.DrawingArea drawingarea15;

		private global::Gtk.DrawingArea drawingarea14;

		private global::Gtk.VBox vbox14;

		private global::Gtk.HBox hbox30;

		private global::Gtk.Label lblapeinst;

		private global::Gtk.Entry entapeinst;

		private global::Gtk.HBox hbox31;

		private global::Gtk.Label lblfechnacinst;

		private global::Gtk.Entry entry9;

		private global::Gtk.VBox vbox19;

		private global::Gtk.DrawingArea drawingarea4;

		private global::Gtk.DrawingArea drawingarea5;

		private global::Gtk.HBox hbox22;

		private global::Gtk.VBox vbox12;

		private global::Gtk.DrawingArea drawingarea13;

		private global::Gtk.DrawingArea drawingarea12;

		private global::Gtk.VBox vbox15;

		private global::Gtk.HBox hbox32;

		private global::Gtk.Label lblsexoinst;

		private global::Gtk.Entry entsexoinst;

		private global::Gtk.HBox hbox33;

		private global::Gtk.Label lbltlfinst;

		private global::Gtk.HBox hbox35;

		private global::Gtk.ComboBox combotlfinst;

		private global::Gtk.Entry enttlfinst;

		private global::Gtk.VBox vbox20;

		private global::Gtk.DrawingArea drawingarea6;

		private global::Gtk.DrawingArea drawingarea7;

		private global::Gtk.HBox hbox23;

		private global::Gtk.VBox vbox17;

		private global::Gtk.DrawingArea drawingarea11;

		private global::Gtk.DrawingArea drawingarea10;

		private global::Gtk.VBox vbox16;

		private global::Gtk.HBox hbox34;

		private global::Gtk.Label lbldireccioninst;

		private global::Gtk.Entry entdireccioninst;

		private global::Gtk.Button btnactualizarinst;

		private global::Gtk.VBox vbox21;

		private global::Gtk.DrawingArea drawingarea8;

		private global::Gtk.DrawingArea drawingarea9;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget ProyectoDamageDefinitivo.ActualizarInstructor
			this.Name = "ProyectoDamageDefinitivo.ActualizarInstructor";
			this.Title = global::Mono.Unix.Catalog.GetString("ActualizarInstructor");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child ProyectoDamageDefinitivo.ActualizarInstructor.Gtk.Container+ContainerChild
			this.vbox9 = new global::Gtk.VBox();
			this.vbox9.Name = "vbox9";
			this.vbox9.Spacing = 6;
			// Container child vbox9.Gtk.Box+BoxChild
			this.hbox21 = new global::Gtk.HBox();
			this.hbox21.Name = "hbox21";
			this.hbox21.Spacing = 6;
			// Container child hbox21.Gtk.Box+BoxChild
			this.drawingarea18 = new global::Gtk.DrawingArea();
			this.drawingarea18.Name = "drawingarea18";
			this.hbox21.Add(this.drawingarea18);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox21[this.drawingarea18]));
			w1.Position = 0;
			// Container child hbox21.Gtk.Box+BoxChild
			this.lblactualizarinstructor = new global::Gtk.Label();
			this.lblactualizarinstructor.Name = "lblactualizarinstructor";
			this.lblactualizarinstructor.LabelProp = global::Mono.Unix.Catalog.GetString("Archivo Instructores");
			this.hbox21.Add(this.lblactualizarinstructor);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox21[this.lblactualizarinstructor]));
			w2.Position = 1;
			// Container child hbox21.Gtk.Box+BoxChild
			this.drawingarea1 = new global::Gtk.DrawingArea();
			this.drawingarea1.Name = "drawingarea1";
			this.hbox21.Add(this.drawingarea1);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox21[this.drawingarea1]));
			w3.Position = 2;
			this.vbox9.Add(this.hbox21);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox9[this.hbox21]));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			// Container child vbox9.Gtk.Box+BoxChild
			this.hbox24 = new global::Gtk.HBox();
			this.hbox24.Name = "hbox24";
			this.hbox24.Spacing = 6;
			// Container child hbox24.Gtk.Box+BoxChild
			this.vbox10 = new global::Gtk.VBox();
			this.vbox10.Name = "vbox10";
			this.vbox10.Spacing = 6;
			// Container child vbox10.Gtk.Box+BoxChild
			this.hbox26 = new global::Gtk.HBox();
			this.hbox26.Name = "hbox26";
			this.hbox26.Spacing = 6;
			// Container child hbox26.Gtk.Box+BoxChild
			this.drawingarea17 = new global::Gtk.DrawingArea();
			this.drawingarea17.Name = "drawingarea17";
			this.hbox26.Add(this.drawingarea17);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox26[this.drawingarea17]));
			w5.Position = 0;
			this.vbox10.Add(this.hbox26);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox10[this.hbox26]));
			w6.Position = 0;
			// Container child vbox10.Gtk.Box+BoxChild
			this.drawingarea16 = new global::Gtk.DrawingArea();
			this.drawingarea16.Name = "drawingarea16";
			this.vbox10.Add(this.drawingarea16);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox10[this.drawingarea16]));
			w7.Position = 1;
			this.hbox24.Add(this.vbox10);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox24[this.vbox10]));
			w8.Position = 0;
			// Container child hbox24.Gtk.Box+BoxChild
			this.vbox13 = new global::Gtk.VBox();
			this.vbox13.Name = "vbox13";
			this.vbox13.Spacing = 6;
			// Container child vbox13.Gtk.Box+BoxChild
			this.hbox27 = new global::Gtk.HBox();
			this.hbox27.Name = "hbox27";
			this.hbox27.Spacing = 6;
			// Container child hbox27.Gtk.Box+BoxChild
			this.lblcedins = new global::Gtk.Label();
			this.lblcedins.Name = "lblcedins";
			this.lblcedins.LabelProp = global::Mono.Unix.Catalog.GetString("Cedula");
			this.hbox27.Add(this.lblcedins);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox27[this.lblcedins]));
			w9.Position = 0;
			w9.Expand = false;
			w9.Fill = false;
			// Container child hbox27.Gtk.Box+BoxChild
			this.entcedins = new global::Gtk.Entry();
			this.entcedins.CanFocus = true;
			this.entcedins.Name = "entcedins";
			this.entcedins.IsEditable = true;
			this.entcedins.InvisibleChar = '●';
			this.hbox27.Add(this.entcedins);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox27[this.entcedins]));
			w10.Position = 1;
			this.vbox13.Add(this.hbox27);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox13[this.hbox27]));
			w11.Position = 0;
			w11.Expand = false;
			w11.Fill = false;
			// Container child vbox13.Gtk.Box+BoxChild
			this.hbox29 = new global::Gtk.HBox();
			this.hbox29.Name = "hbox29";
			this.hbox29.Spacing = 6;
			// Container child hbox29.Gtk.Box+BoxChild
			this.lblnomins = new global::Gtk.Label();
			this.lblnomins.Name = "lblnomins";
			this.lblnomins.LabelProp = global::Mono.Unix.Catalog.GetString("Nombres");
			this.hbox29.Add(this.lblnomins);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox29[this.lblnomins]));
			w12.Position = 0;
			w12.Expand = false;
			w12.Fill = false;
			// Container child hbox29.Gtk.Box+BoxChild
			this.entnomins = new global::Gtk.Entry();
			this.entnomins.CanFocus = true;
			this.entnomins.Name = "entnomins";
			this.entnomins.IsEditable = true;
			this.entnomins.InvisibleChar = '●';
			this.hbox29.Add(this.entnomins);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox29[this.entnomins]));
			w13.Position = 1;
			this.vbox13.Add(this.hbox29);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vbox13[this.hbox29]));
			w14.Position = 1;
			w14.Expand = false;
			w14.Fill = false;
			this.hbox24.Add(this.vbox13);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.hbox24[this.vbox13]));
			w15.Position = 1;
			// Container child hbox24.Gtk.Box+BoxChild
			this.vbox18 = new global::Gtk.VBox();
			this.vbox18.Name = "vbox18";
			this.vbox18.Spacing = 6;
			// Container child vbox18.Gtk.Box+BoxChild
			this.hbox28 = new global::Gtk.HBox();
			this.hbox28.Name = "hbox28";
			this.hbox28.Spacing = 6;
			// Container child hbox28.Gtk.Box+BoxChild
			this.drawingarea2 = new global::Gtk.DrawingArea();
			this.drawingarea2.Name = "drawingarea2";
			this.hbox28.Add(this.drawingarea2);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.hbox28[this.drawingarea2]));
			w16.Position = 0;
			this.vbox18.Add(this.hbox28);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.vbox18[this.hbox28]));
			w17.Position = 0;
			// Container child vbox18.Gtk.Box+BoxChild
			this.drawingarea3 = new global::Gtk.DrawingArea();
			this.drawingarea3.Name = "drawingarea3";
			this.vbox18.Add(this.drawingarea3);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.vbox18[this.drawingarea3]));
			w18.Position = 1;
			this.hbox24.Add(this.vbox18);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.hbox24[this.vbox18]));
			w19.Position = 2;
			this.vbox9.Add(this.hbox24);
			global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.vbox9[this.hbox24]));
			w20.Position = 1;
			w20.Expand = false;
			w20.Fill = false;
			// Container child vbox9.Gtk.Box+BoxChild
			this.hbox25 = new global::Gtk.HBox();
			this.hbox25.Name = "hbox25";
			this.hbox25.Spacing = 6;
			// Container child hbox25.Gtk.Box+BoxChild
			this.vbox11 = new global::Gtk.VBox();
			this.vbox11.Name = "vbox11";
			this.vbox11.Spacing = 6;
			// Container child vbox11.Gtk.Box+BoxChild
			this.drawingarea15 = new global::Gtk.DrawingArea();
			this.drawingarea15.Name = "drawingarea15";
			this.vbox11.Add(this.drawingarea15);
			global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.vbox11[this.drawingarea15]));
			w21.Position = 0;
			// Container child vbox11.Gtk.Box+BoxChild
			this.drawingarea14 = new global::Gtk.DrawingArea();
			this.drawingarea14.Name = "drawingarea14";
			this.vbox11.Add(this.drawingarea14);
			global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.vbox11[this.drawingarea14]));
			w22.Position = 1;
			this.hbox25.Add(this.vbox11);
			global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.hbox25[this.vbox11]));
			w23.Position = 0;
			// Container child hbox25.Gtk.Box+BoxChild
			this.vbox14 = new global::Gtk.VBox();
			this.vbox14.Name = "vbox14";
			this.vbox14.Spacing = 6;
			// Container child vbox14.Gtk.Box+BoxChild
			this.hbox30 = new global::Gtk.HBox();
			this.hbox30.Name = "hbox30";
			this.hbox30.Spacing = 6;
			// Container child hbox30.Gtk.Box+BoxChild
			this.lblapeinst = new global::Gtk.Label();
			this.lblapeinst.Name = "lblapeinst";
			this.lblapeinst.LabelProp = global::Mono.Unix.Catalog.GetString("Apellidos");
			this.hbox30.Add(this.lblapeinst);
			global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.hbox30[this.lblapeinst]));
			w24.Position = 0;
			w24.Expand = false;
			w24.Fill = false;
			// Container child hbox30.Gtk.Box+BoxChild
			this.entapeinst = new global::Gtk.Entry();
			this.entapeinst.CanFocus = true;
			this.entapeinst.Name = "entapeinst";
			this.entapeinst.IsEditable = true;
			this.entapeinst.InvisibleChar = '●';
			this.hbox30.Add(this.entapeinst);
			global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.hbox30[this.entapeinst]));
			w25.Position = 1;
			this.vbox14.Add(this.hbox30);
			global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.vbox14[this.hbox30]));
			w26.Position = 0;
			w26.Expand = false;
			w26.Fill = false;
			// Container child vbox14.Gtk.Box+BoxChild
			this.hbox31 = new global::Gtk.HBox();
			this.hbox31.Name = "hbox31";
			this.hbox31.Spacing = 6;
			// Container child hbox31.Gtk.Box+BoxChild
			this.lblfechnacinst = new global::Gtk.Label();
			this.lblfechnacinst.Name = "lblfechnacinst";
			this.lblfechnacinst.LabelProp = global::Mono.Unix.Catalog.GetString("Fecha de \nnacimiento\n");
			this.hbox31.Add(this.lblfechnacinst);
			global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.hbox31[this.lblfechnacinst]));
			w27.Position = 0;
			w27.Expand = false;
			w27.Fill = false;
			// Container child hbox31.Gtk.Box+BoxChild
			this.entry9 = new global::Gtk.Entry();
			this.entry9.CanFocus = true;
			this.entry9.Name = "entry9";
			this.entry9.IsEditable = true;
			this.entry9.InvisibleChar = '●';
			this.hbox31.Add(this.entry9);
			global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.hbox31[this.entry9]));
			w28.Position = 1;
			this.vbox14.Add(this.hbox31);
			global::Gtk.Box.BoxChild w29 = ((global::Gtk.Box.BoxChild)(this.vbox14[this.hbox31]));
			w29.Position = 1;
			w29.Expand = false;
			w29.Fill = false;
			this.hbox25.Add(this.vbox14);
			global::Gtk.Box.BoxChild w30 = ((global::Gtk.Box.BoxChild)(this.hbox25[this.vbox14]));
			w30.Position = 1;
			// Container child hbox25.Gtk.Box+BoxChild
			this.vbox19 = new global::Gtk.VBox();
			this.vbox19.Name = "vbox19";
			this.vbox19.Spacing = 6;
			// Container child vbox19.Gtk.Box+BoxChild
			this.drawingarea4 = new global::Gtk.DrawingArea();
			this.drawingarea4.Name = "drawingarea4";
			this.vbox19.Add(this.drawingarea4);
			global::Gtk.Box.BoxChild w31 = ((global::Gtk.Box.BoxChild)(this.vbox19[this.drawingarea4]));
			w31.Position = 0;
			// Container child vbox19.Gtk.Box+BoxChild
			this.drawingarea5 = new global::Gtk.DrawingArea();
			this.drawingarea5.Name = "drawingarea5";
			this.vbox19.Add(this.drawingarea5);
			global::Gtk.Box.BoxChild w32 = ((global::Gtk.Box.BoxChild)(this.vbox19[this.drawingarea5]));
			w32.Position = 1;
			this.hbox25.Add(this.vbox19);
			global::Gtk.Box.BoxChild w33 = ((global::Gtk.Box.BoxChild)(this.hbox25[this.vbox19]));
			w33.Position = 2;
			this.vbox9.Add(this.hbox25);
			global::Gtk.Box.BoxChild w34 = ((global::Gtk.Box.BoxChild)(this.vbox9[this.hbox25]));
			w34.Position = 2;
			w34.Expand = false;
			w34.Fill = false;
			// Container child vbox9.Gtk.Box+BoxChild
			this.hbox22 = new global::Gtk.HBox();
			this.hbox22.Name = "hbox22";
			this.hbox22.Spacing = 6;
			// Container child hbox22.Gtk.Box+BoxChild
			this.vbox12 = new global::Gtk.VBox();
			this.vbox12.Name = "vbox12";
			this.vbox12.Spacing = 6;
			// Container child vbox12.Gtk.Box+BoxChild
			this.drawingarea13 = new global::Gtk.DrawingArea();
			this.drawingarea13.Name = "drawingarea13";
			this.vbox12.Add(this.drawingarea13);
			global::Gtk.Box.BoxChild w35 = ((global::Gtk.Box.BoxChild)(this.vbox12[this.drawingarea13]));
			w35.Position = 0;
			// Container child vbox12.Gtk.Box+BoxChild
			this.drawingarea12 = new global::Gtk.DrawingArea();
			this.drawingarea12.Name = "drawingarea12";
			this.vbox12.Add(this.drawingarea12);
			global::Gtk.Box.BoxChild w36 = ((global::Gtk.Box.BoxChild)(this.vbox12[this.drawingarea12]));
			w36.Position = 1;
			this.hbox22.Add(this.vbox12);
			global::Gtk.Box.BoxChild w37 = ((global::Gtk.Box.BoxChild)(this.hbox22[this.vbox12]));
			w37.Position = 0;
			// Container child hbox22.Gtk.Box+BoxChild
			this.vbox15 = new global::Gtk.VBox();
			this.vbox15.Name = "vbox15";
			this.vbox15.Spacing = 6;
			// Container child vbox15.Gtk.Box+BoxChild
			this.hbox32 = new global::Gtk.HBox();
			this.hbox32.Name = "hbox32";
			this.hbox32.Spacing = 6;
			// Container child hbox32.Gtk.Box+BoxChild
			this.lblsexoinst = new global::Gtk.Label();
			this.lblsexoinst.Name = "lblsexoinst";
			this.lblsexoinst.LabelProp = global::Mono.Unix.Catalog.GetString("Sexo");
			this.hbox32.Add(this.lblsexoinst);
			global::Gtk.Box.BoxChild w38 = ((global::Gtk.Box.BoxChild)(this.hbox32[this.lblsexoinst]));
			w38.Position = 0;
			w38.Expand = false;
			w38.Fill = false;
			// Container child hbox32.Gtk.Box+BoxChild
			this.entsexoinst = new global::Gtk.Entry();
			this.entsexoinst.CanFocus = true;
			this.entsexoinst.Name = "entsexoinst";
			this.entsexoinst.IsEditable = true;
			this.entsexoinst.InvisibleChar = '●';
			this.hbox32.Add(this.entsexoinst);
			global::Gtk.Box.BoxChild w39 = ((global::Gtk.Box.BoxChild)(this.hbox32[this.entsexoinst]));
			w39.Position = 1;
			this.vbox15.Add(this.hbox32);
			global::Gtk.Box.BoxChild w40 = ((global::Gtk.Box.BoxChild)(this.vbox15[this.hbox32]));
			w40.Position = 0;
			w40.Expand = false;
			w40.Fill = false;
			// Container child vbox15.Gtk.Box+BoxChild
			this.hbox33 = new global::Gtk.HBox();
			this.hbox33.Name = "hbox33";
			this.hbox33.Spacing = 6;
			// Container child hbox33.Gtk.Box+BoxChild
			this.lbltlfinst = new global::Gtk.Label();
			this.lbltlfinst.Name = "lbltlfinst";
			this.lbltlfinst.LabelProp = global::Mono.Unix.Catalog.GetString("Teléfono");
			this.hbox33.Add(this.lbltlfinst);
			global::Gtk.Box.BoxChild w41 = ((global::Gtk.Box.BoxChild)(this.hbox33[this.lbltlfinst]));
			w41.Position = 0;
			w41.Expand = false;
			w41.Fill = false;
			// Container child hbox33.Gtk.Box+BoxChild
			this.hbox35 = new global::Gtk.HBox();
			this.hbox35.Name = "hbox35";
			this.hbox35.Spacing = 6;
			// Container child hbox35.Gtk.Box+BoxChild
			this.combotlfinst = global::Gtk.ComboBox.NewText();
			this.combotlfinst.AppendText(global::Mono.Unix.Catalog.GetString("0424"));
			this.combotlfinst.AppendText(global::Mono.Unix.Catalog.GetString("0414"));
			this.combotlfinst.AppendText(global::Mono.Unix.Catalog.GetString("0426"));
			this.combotlfinst.AppendText(global::Mono.Unix.Catalog.GetString("0416"));
			this.combotlfinst.AppendText(global::Mono.Unix.Catalog.GetString("0412"));
			this.combotlfinst.AppendText(global::Mono.Unix.Catalog.GetString("0251"));
			this.combotlfinst.Name = "combotlfinst";
			this.combotlfinst.Active = 0;
			this.hbox35.Add(this.combotlfinst);
			global::Gtk.Box.BoxChild w42 = ((global::Gtk.Box.BoxChild)(this.hbox35[this.combotlfinst]));
			w42.Position = 0;
			w42.Expand = false;
			w42.Fill = false;
			// Container child hbox35.Gtk.Box+BoxChild
			this.enttlfinst = new global::Gtk.Entry();
			this.enttlfinst.CanFocus = true;
			this.enttlfinst.Name = "enttlfinst";
			this.enttlfinst.IsEditable = true;
			this.enttlfinst.InvisibleChar = '●';
			this.hbox35.Add(this.enttlfinst);
			global::Gtk.Box.BoxChild w43 = ((global::Gtk.Box.BoxChild)(this.hbox35[this.enttlfinst]));
			w43.Position = 1;
			this.hbox33.Add(this.hbox35);
			global::Gtk.Box.BoxChild w44 = ((global::Gtk.Box.BoxChild)(this.hbox33[this.hbox35]));
			w44.Position = 1;
			this.vbox15.Add(this.hbox33);
			global::Gtk.Box.BoxChild w45 = ((global::Gtk.Box.BoxChild)(this.vbox15[this.hbox33]));
			w45.Position = 1;
			w45.Expand = false;
			w45.Fill = false;
			this.hbox22.Add(this.vbox15);
			global::Gtk.Box.BoxChild w46 = ((global::Gtk.Box.BoxChild)(this.hbox22[this.vbox15]));
			w46.Position = 1;
			// Container child hbox22.Gtk.Box+BoxChild
			this.vbox20 = new global::Gtk.VBox();
			this.vbox20.Name = "vbox20";
			this.vbox20.Spacing = 6;
			// Container child vbox20.Gtk.Box+BoxChild
			this.drawingarea6 = new global::Gtk.DrawingArea();
			this.drawingarea6.Name = "drawingarea6";
			this.vbox20.Add(this.drawingarea6);
			global::Gtk.Box.BoxChild w47 = ((global::Gtk.Box.BoxChild)(this.vbox20[this.drawingarea6]));
			w47.Position = 0;
			// Container child vbox20.Gtk.Box+BoxChild
			this.drawingarea7 = new global::Gtk.DrawingArea();
			this.drawingarea7.Name = "drawingarea7";
			this.vbox20.Add(this.drawingarea7);
			global::Gtk.Box.BoxChild w48 = ((global::Gtk.Box.BoxChild)(this.vbox20[this.drawingarea7]));
			w48.Position = 1;
			this.hbox22.Add(this.vbox20);
			global::Gtk.Box.BoxChild w49 = ((global::Gtk.Box.BoxChild)(this.hbox22[this.vbox20]));
			w49.Position = 2;
			this.vbox9.Add(this.hbox22);
			global::Gtk.Box.BoxChild w50 = ((global::Gtk.Box.BoxChild)(this.vbox9[this.hbox22]));
			w50.Position = 3;
			w50.Expand = false;
			w50.Fill = false;
			// Container child vbox9.Gtk.Box+BoxChild
			this.hbox23 = new global::Gtk.HBox();
			this.hbox23.Name = "hbox23";
			this.hbox23.Spacing = 6;
			// Container child hbox23.Gtk.Box+BoxChild
			this.vbox17 = new global::Gtk.VBox();
			this.vbox17.Name = "vbox17";
			this.vbox17.Spacing = 6;
			// Container child vbox17.Gtk.Box+BoxChild
			this.drawingarea11 = new global::Gtk.DrawingArea();
			this.drawingarea11.Name = "drawingarea11";
			this.vbox17.Add(this.drawingarea11);
			global::Gtk.Box.BoxChild w51 = ((global::Gtk.Box.BoxChild)(this.vbox17[this.drawingarea11]));
			w51.Position = 0;
			// Container child vbox17.Gtk.Box+BoxChild
			this.drawingarea10 = new global::Gtk.DrawingArea();
			this.drawingarea10.Name = "drawingarea10";
			this.vbox17.Add(this.drawingarea10);
			global::Gtk.Box.BoxChild w52 = ((global::Gtk.Box.BoxChild)(this.vbox17[this.drawingarea10]));
			w52.Position = 1;
			this.hbox23.Add(this.vbox17);
			global::Gtk.Box.BoxChild w53 = ((global::Gtk.Box.BoxChild)(this.hbox23[this.vbox17]));
			w53.Position = 0;
			// Container child hbox23.Gtk.Box+BoxChild
			this.vbox16 = new global::Gtk.VBox();
			this.vbox16.Name = "vbox16";
			this.vbox16.Spacing = 6;
			// Container child vbox16.Gtk.Box+BoxChild
			this.hbox34 = new global::Gtk.HBox();
			this.hbox34.Name = "hbox34";
			this.hbox34.Spacing = 6;
			// Container child hbox34.Gtk.Box+BoxChild
			this.lbldireccioninst = new global::Gtk.Label();
			this.lbldireccioninst.Name = "lbldireccioninst";
			this.lbldireccioninst.LabelProp = global::Mono.Unix.Catalog.GetString("Direccion");
			this.hbox34.Add(this.lbldireccioninst);
			global::Gtk.Box.BoxChild w54 = ((global::Gtk.Box.BoxChild)(this.hbox34[this.lbldireccioninst]));
			w54.Position = 0;
			w54.Expand = false;
			w54.Fill = false;
			// Container child hbox34.Gtk.Box+BoxChild
			this.entdireccioninst = new global::Gtk.Entry();
			this.entdireccioninst.CanFocus = true;
			this.entdireccioninst.Name = "entdireccioninst";
			this.entdireccioninst.IsEditable = true;
			this.entdireccioninst.InvisibleChar = '●';
			this.hbox34.Add(this.entdireccioninst);
			global::Gtk.Box.BoxChild w55 = ((global::Gtk.Box.BoxChild)(this.hbox34[this.entdireccioninst]));
			w55.Position = 1;
			this.vbox16.Add(this.hbox34);
			global::Gtk.Box.BoxChild w56 = ((global::Gtk.Box.BoxChild)(this.vbox16[this.hbox34]));
			w56.Position = 0;
			w56.Expand = false;
			w56.Fill = false;
			// Container child vbox16.Gtk.Box+BoxChild
			this.btnactualizarinst = new global::Gtk.Button();
			this.btnactualizarinst.CanFocus = true;
			this.btnactualizarinst.Name = "btnactualizarinst";
			this.btnactualizarinst.UseUnderline = true;
			this.btnactualizarinst.Label = global::Mono.Unix.Catalog.GetString("Actualizar");
			this.vbox16.Add(this.btnactualizarinst);
			global::Gtk.Box.BoxChild w57 = ((global::Gtk.Box.BoxChild)(this.vbox16[this.btnactualizarinst]));
			w57.Position = 1;
			w57.Expand = false;
			w57.Fill = false;
			this.hbox23.Add(this.vbox16);
			global::Gtk.Box.BoxChild w58 = ((global::Gtk.Box.BoxChild)(this.hbox23[this.vbox16]));
			w58.Position = 1;
			w58.Expand = false;
			w58.Fill = false;
			// Container child hbox23.Gtk.Box+BoxChild
			this.vbox21 = new global::Gtk.VBox();
			this.vbox21.Name = "vbox21";
			this.vbox21.Spacing = 6;
			// Container child vbox21.Gtk.Box+BoxChild
			this.drawingarea8 = new global::Gtk.DrawingArea();
			this.drawingarea8.Name = "drawingarea8";
			this.vbox21.Add(this.drawingarea8);
			global::Gtk.Box.BoxChild w59 = ((global::Gtk.Box.BoxChild)(this.vbox21[this.drawingarea8]));
			w59.Position = 0;
			// Container child vbox21.Gtk.Box+BoxChild
			this.drawingarea9 = new global::Gtk.DrawingArea();
			this.drawingarea9.Name = "drawingarea9";
			this.vbox21.Add(this.drawingarea9);
			global::Gtk.Box.BoxChild w60 = ((global::Gtk.Box.BoxChild)(this.vbox21[this.drawingarea9]));
			w60.Position = 1;
			this.hbox23.Add(this.vbox21);
			global::Gtk.Box.BoxChild w61 = ((global::Gtk.Box.BoxChild)(this.hbox23[this.vbox21]));
			w61.Position = 2;
			this.vbox9.Add(this.hbox23);
			global::Gtk.Box.BoxChild w62 = ((global::Gtk.Box.BoxChild)(this.vbox9[this.hbox23]));
			w62.Position = 4;
			w62.Expand = false;
			w62.Fill = false;
			this.Add(this.vbox9);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 307;
			this.Show();
			this.btnactualizarinst.Clicked += new global::System.EventHandler(this.OnBtnactualizarinstClicked);
		}
	}
}
