
// This file has been generated by the GUI designer. Do not modify.
namespace ProyectoDamageDefinitivo
{
	public partial class ArchivosMaestros
	{
		private global::Gtk.VBox vbox8;

		private global::Gtk.HBox hbox16;

		private global::Gtk.Label lblarchivo;

		private global::Gtk.HBox hbox18;

		private global::Gtk.Button btnarchinstructor;

		private global::Gtk.Button btnarchestudiante;

		private global::Gtk.HBox hbox19;

		private global::Gtk.Button btnarchusuario;

		private global::Gtk.Button btnarchcurso;

		private global::Gtk.HBox hbox20;

		private global::Gtk.Button btnarchgrupo;

		private global::Gtk.Button btnarchturno;

		private global::Gtk.Button btnsalir3;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget ProyectoDamageDefinitivo.ArchivosMaestros
			this.Name = "ProyectoDamageDefinitivo.ArchivosMaestros";
			this.Title = global::Mono.Unix.Catalog.GetString("ArchivosMaestros");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child ProyectoDamageDefinitivo.ArchivosMaestros.Gtk.Container+ContainerChild
			this.vbox8 = new global::Gtk.VBox();
			this.vbox8.Name = "vbox8";
			this.vbox8.Spacing = 6;
			// Container child vbox8.Gtk.Box+BoxChild
			this.hbox16 = new global::Gtk.HBox();
			this.hbox16.Name = "hbox16";
			this.hbox16.Spacing = 6;
			// Container child hbox16.Gtk.Box+BoxChild
			this.lblarchivo = new global::Gtk.Label();
			this.lblarchivo.Name = "lblarchivo";
			this.lblarchivo.LabelProp = global::Mono.Unix.Catalog.GetString("Seleccione un archivo");
			this.hbox16.Add(this.lblarchivo);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox16[this.lblarchivo]));
			w1.Position = 0;
			this.vbox8.Add(this.hbox16);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox8[this.hbox16]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox8.Gtk.Box+BoxChild
			this.hbox18 = new global::Gtk.HBox();
			this.hbox18.Name = "hbox18";
			this.hbox18.Spacing = 6;
			// Container child hbox18.Gtk.Box+BoxChild
			this.btnarchinstructor = new global::Gtk.Button();
			this.btnarchinstructor.CanFocus = true;
			this.btnarchinstructor.Name = "btnarchinstructor";
			this.btnarchinstructor.UseUnderline = true;
			this.btnarchinstructor.Label = global::Mono.Unix.Catalog.GetString("Instructor");
			this.hbox18.Add(this.btnarchinstructor);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox18[this.btnarchinstructor]));
			w3.Position = 0;
			// Container child hbox18.Gtk.Box+BoxChild
			this.btnarchestudiante = new global::Gtk.Button();
			this.btnarchestudiante.CanFocus = true;
			this.btnarchestudiante.Name = "btnarchestudiante";
			this.btnarchestudiante.UseUnderline = true;
			this.btnarchestudiante.Label = global::Mono.Unix.Catalog.GetString("Estudiante");
			this.hbox18.Add(this.btnarchestudiante);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox18[this.btnarchestudiante]));
			w4.Position = 1;
			this.vbox8.Add(this.hbox18);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox8[this.hbox18]));
			w5.Position = 1;
			w5.Expand = false;
			w5.Fill = false;
			// Container child vbox8.Gtk.Box+BoxChild
			this.hbox19 = new global::Gtk.HBox();
			this.hbox19.Name = "hbox19";
			this.hbox19.Spacing = 6;
			// Container child hbox19.Gtk.Box+BoxChild
			this.btnarchusuario = new global::Gtk.Button();
			this.btnarchusuario.CanFocus = true;
			this.btnarchusuario.Name = "btnarchusuario";
			this.btnarchusuario.UseUnderline = true;
			this.btnarchusuario.Label = global::Mono.Unix.Catalog.GetString("Usuario");
			this.hbox19.Add(this.btnarchusuario);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox19[this.btnarchusuario]));
			w6.Position = 0;
			// Container child hbox19.Gtk.Box+BoxChild
			this.btnarchcurso = new global::Gtk.Button();
			this.btnarchcurso.CanFocus = true;
			this.btnarchcurso.Name = "btnarchcurso";
			this.btnarchcurso.UseUnderline = true;
			this.btnarchcurso.Label = global::Mono.Unix.Catalog.GetString("Curso");
			this.hbox19.Add(this.btnarchcurso);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox19[this.btnarchcurso]));
			w7.Position = 1;
			this.vbox8.Add(this.hbox19);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox8[this.hbox19]));
			w8.Position = 2;
			w8.Expand = false;
			w8.Fill = false;
			// Container child vbox8.Gtk.Box+BoxChild
			this.hbox20 = new global::Gtk.HBox();
			this.hbox20.Name = "hbox20";
			this.hbox20.Spacing = 6;
			// Container child hbox20.Gtk.Box+BoxChild
			this.btnarchgrupo = new global::Gtk.Button();
			this.btnarchgrupo.CanFocus = true;
			this.btnarchgrupo.Name = "btnarchgrupo";
			this.btnarchgrupo.UseUnderline = true;
			this.btnarchgrupo.Label = global::Mono.Unix.Catalog.GetString("Grupo");
			this.hbox20.Add(this.btnarchgrupo);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox20[this.btnarchgrupo]));
			w9.Position = 0;
			// Container child hbox20.Gtk.Box+BoxChild
			this.btnarchturno = new global::Gtk.Button();
			this.btnarchturno.CanFocus = true;
			this.btnarchturno.Name = "btnarchturno";
			this.btnarchturno.UseUnderline = true;
			this.btnarchturno.Label = global::Mono.Unix.Catalog.GetString("Turno");
			this.hbox20.Add(this.btnarchturno);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox20[this.btnarchturno]));
			w10.Position = 1;
			this.vbox8.Add(this.hbox20);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox8[this.hbox20]));
			w11.Position = 3;
			w11.Expand = false;
			w11.Fill = false;
			// Container child vbox8.Gtk.Box+BoxChild
			this.btnsalir3 = new global::Gtk.Button();
			this.btnsalir3.CanFocus = true;
			this.btnsalir3.Name = "btnsalir3";
			this.btnsalir3.UseUnderline = true;
			this.btnsalir3.Label = global::Mono.Unix.Catalog.GetString("Salir");
			this.vbox8.Add(this.btnsalir3);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox8[this.btnsalir3]));
			w12.Position = 4;
			w12.Expand = false;
			this.Add(this.vbox8);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show();
			this.btnarchinstructor.Clicked += new global::System.EventHandler(this.OnBtnarchinstructorClicked);
			this.btnarchestudiante.Clicked += new global::System.EventHandler(this.OnBtnarchestudianteClicked);
			this.btnarchusuario.Clicked += new global::System.EventHandler(this.OnBtnarchusuarioClicked);
			this.btnarchcurso.Clicked += new global::System.EventHandler(this.OnBtnarchcursoClicked);
			this.btnarchgrupo.Clicked += new global::System.EventHandler(this.OnBtnarchgrupoClicked);
			this.btnarchturno.Clicked += new global::System.EventHandler(this.OnBtnarchturnoClicked);
			this.btnsalir3.Clicked += new global::System.EventHandler(this.OnBtnsalir3Clicked);
		}
	}
}
