
// This file has been generated by the GUI designer. Do not modify.
namespace ProYectoX
{
	public partial class Validaciones
	{
		protected virtual void Build()
		{
			
			// Widget ProYectoX.Validaciones
		
		}
	}
}
