
// This file has been generated by the GUI designer. Do not modify.
namespace ProYectoX
{
	public partial class ReportesGrupos
	{
		private global::Gtk.VBox vbox1;

		private global::Gtk.HSeparator hseparator19;

		private global::Gtk.Label label1;

		private global::Gtk.HSeparator hseparator20;

		private global::Gtk.ScrolledWindow GtkScrolledWindow;

		private global::Gtk.TreeView treart;

		private global::Gtk.HSeparator hseparator21;

		private global::Gtk.HBox hbox6;

		private global::Gtk.Button btncaa;

		private global::Gtk.Button btnsss;

		private global::Gtk.HSeparator hseparator22;

		private global::Gtk.HBox hbox1;

		private global::Gtk.Label lblfecha;

		private global::Gtk.Label lblhora;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget ProYectoX.ReportesGrupos
			this.Name = "ProYectoX.ReportesGrupos";
			this.Title = global::Mono.Unix.Catalog.GetString("ReportesGrupos");
			this.WindowPosition = ((global::Gtk.WindowPosition)(1));
			// Container child ProYectoX.ReportesGrupos.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hseparator19 = new global::Gtk.HSeparator();
			this.hseparator19.Name = "hseparator19";
			this.vbox1.Add(this.hseparator19);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hseparator19]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.label1 = new global::Gtk.Label();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString("Reporte de cursos culminados a la fecha actual");
			this.vbox1.Add(this.label1);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.label1]));
			w2.Position = 1;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hseparator20 = new global::Gtk.HSeparator();
			this.hseparator20.Name = "hseparator20";
			this.vbox1.Add(this.hseparator20);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hseparator20]));
			w3.Position = 2;
			w3.Expand = false;
			w3.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.treart = new global::Gtk.TreeView();
			this.treart.CanFocus = true;
			this.treart.Name = "treart";
			this.GtkScrolledWindow.Add(this.treart);
			this.vbox1.Add(this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.GtkScrolledWindow]));
			w5.Position = 3;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hseparator21 = new global::Gtk.HSeparator();
			this.hseparator21.Name = "hseparator21";
			this.vbox1.Add(this.hseparator21);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hseparator21]));
			w6.Position = 4;
			w6.Expand = false;
			w6.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox6 = new global::Gtk.HBox();
			this.hbox6.Name = "hbox6";
			this.hbox6.Spacing = 6;
			// Container child hbox6.Gtk.Box+BoxChild
			this.btncaa = new global::Gtk.Button();
			this.btncaa.CanFocus = true;
			this.btncaa.Name = "btncaa";
			this.btncaa.UseUnderline = true;
			this.btncaa.Label = global::Mono.Unix.Catalog.GetString("Atras");
			this.hbox6.Add(this.btncaa);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox6[this.btncaa]));
			w7.Position = 0;
			// Container child hbox6.Gtk.Box+BoxChild
			this.btnsss = new global::Gtk.Button();
			this.btnsss.CanFocus = true;
			this.btnsss.Name = "btnsss";
			this.btnsss.UseUnderline = true;
			this.btnsss.Label = global::Mono.Unix.Catalog.GetString("Salir");
			this.hbox6.Add(this.btnsss);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox6[this.btnsss]));
			w8.Position = 1;
			this.vbox1.Add(this.hbox6);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox6]));
			w9.Position = 5;
			w9.Expand = false;
			w9.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hseparator22 = new global::Gtk.HSeparator();
			this.hseparator22.Name = "hseparator22";
			this.vbox1.Add(this.hseparator22);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hseparator22]));
			w10.Position = 6;
			w10.Expand = false;
			w10.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.lblfecha = new global::Gtk.Label();
			this.lblfecha.Name = "lblfecha";
			this.lblfecha.Xpad = 44;
			this.lblfecha.Xalign = 0F;
			this.hbox1.Add(this.lblfecha);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.lblfecha]));
			w11.Position = 0;
			// Container child hbox1.Gtk.Box+BoxChild
			this.lblhora = new global::Gtk.Label();
			this.lblhora.HeightRequest = 28;
			this.lblhora.Name = "lblhora";
			this.lblhora.Xpad = 55;
			this.lblhora.Xalign = 1F;
			this.hbox1.Add(this.lblhora);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.lblhora]));
			w12.Position = 1;
			this.vbox1.Add(this.hbox1);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox1]));
			w13.Position = 7;
			w13.Expand = false;
			w13.Fill = false;
			this.Add(this.vbox1);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 517;
			this.DefaultHeight = 322;
			this.Show();
			this.btncaa.Clicked += new global::System.EventHandler(this.OnBtncaaClicked);
			this.btnsss.Clicked += new global::System.EventHandler(this.OnBtnsssClicked);
		}
	}
}
