
// This file has been generated by the GUI designer. Do not modify.
namespace ProYectoX
{
	public partial class Opciones
	{
		private global::Gtk.VBox vbox3;

		private global::Gtk.Button btnactualizar;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget ProYectoX.Opciones
			this.Name = "ProYectoX.Opciones";
			this.Title = global::Mono.Unix.Catalog.GetString("Opciones");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child ProYectoX.Opciones.Gtk.Container+ContainerChild
			this.vbox3 = new global::Gtk.VBox();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			// Container child vbox3.Gtk.Box+BoxChild
			this.btnactualizar = new global::Gtk.Button();
			this.btnactualizar.CanFocus = true;
			this.btnactualizar.Name = "btnactualizar";
			this.btnactualizar.UseUnderline = true;
			this.btnactualizar.Label = global::Mono.Unix.Catalog.GetString("Actualización");
			this.vbox3.Add(this.btnactualizar);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.btnactualizar]));
			w1.Position = 1;
			w1.Expand = false;
			w1.Fill = false;
			this.Add(this.vbox3);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show();
			this.btnactualizar.Clicked += new global::System.EventHandler(this.OnBtnactualizarClicked);
		}
	}
}
