
// This file has been generated by the GUI designer. Do not modify.
namespace ProYectoX
{
	public partial class ReportesCursos
	{
		private global::Gtk.VBox vbox2;

		private global::Gtk.Label GtkLabel1;

		private global::Gtk.HSeparator hseparator15;

		private global::Gtk.HBox hbox2;

		private global::Gtk.Label lblfechain;

		private global::Gtk.HBox hbox3;

		private global::Gtk.Label lblfechafi;

		private global::Gtk.HSeparator hseparator16;

		private global::Gtk.HBox hbox7;

		private global::Gtk.Calendar calendar1;

		private global::Gtk.Calendar calendar2;

		private global::Gtk.HSeparator hseparator17;

		private global::Gtk.ScrolledWindow GtkScrolledWindow;

		private global::Gtk.TreeView treeview1;

		private global::Gtk.HBox hbox5;

		private global::Gtk.Button bntcan;

		private global::Gtk.Button butsalir;

		private global::Gtk.HSeparator hseparator18;

		private global::Gtk.HBox hbox4;

		private global::Gtk.Label lblfecha;

		private global::Gtk.Label lblhora;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget ProYectoX.ReportesCursos
			this.Name = "ProYectoX.ReportesCursos";
			this.Title = global::Mono.Unix.Catalog.GetString("ReportesCursos");
			this.WindowPosition = ((global::Gtk.WindowPosition)(1));
			// Container child ProYectoX.ReportesCursos.Gtk.Container+ContainerChild
			this.vbox2 = new global::Gtk.VBox();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.GtkLabel1 = new global::Gtk.Label();
			this.GtkLabel1.Name = "GtkLabel1";
			this.GtkLabel1.LabelProp = global::Mono.Unix.Catalog.GetString("<b>REPORTE POR CURSOS</b>");
			this.GtkLabel1.UseMarkup = true;
			this.vbox2.Add(this.GtkLabel1);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.GtkLabel1]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hseparator15 = new global::Gtk.HSeparator();
			this.hseparator15.Name = "hseparator15";
			this.vbox2.Add(this.hseparator15);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.hseparator15]));
			w2.Position = 1;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.lblfechain = new global::Gtk.Label();
			this.lblfechain.Name = "lblfechain";
			this.lblfechain.Xpad = 74;
			this.lblfechain.Ypad = 9;
			this.lblfechain.LabelProp = global::Mono.Unix.Catalog.GetString("FECHA INICIAL");
			this.hbox2.Add(this.lblfechain);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.lblfechain]));
			w3.Position = 0;
			w3.Expand = false;
			w3.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.hbox3 = new global::Gtk.HBox();
			this.hbox3.Name = "hbox3";
			this.hbox3.Spacing = 6;
			// Container child hbox3.Gtk.Box+BoxChild
			this.lblfechafi = new global::Gtk.Label();
			this.lblfechafi.Name = "lblfechafi";
			this.lblfechafi.Xpad = 80;
			this.lblfechafi.LabelProp = global::Mono.Unix.Catalog.GetString("FECHA FINAL");
			this.hbox3.Add(this.lblfechafi);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.lblfechafi]));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			this.hbox2.Add(this.hbox3);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.hbox3]));
			w5.Position = 1;
			w5.Expand = false;
			w5.Fill = false;
			this.vbox2.Add(this.hbox2);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.hbox2]));
			w6.Position = 2;
			w6.Expand = false;
			w6.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hseparator16 = new global::Gtk.HSeparator();
			this.hseparator16.Name = "hseparator16";
			this.vbox2.Add(this.hseparator16);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.hseparator16]));
			w7.Position = 3;
			w7.Expand = false;
			w7.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox7 = new global::Gtk.HBox();
			this.hbox7.Name = "hbox7";
			this.hbox7.Spacing = 6;
			// Container child hbox7.Gtk.Box+BoxChild
			this.calendar1 = new global::Gtk.Calendar();
			this.calendar1.CanFocus = true;
			this.calendar1.Name = "calendar1";
			this.calendar1.DisplayOptions = ((global::Gtk.CalendarDisplayOptions)(35));
			this.hbox7.Add(this.calendar1);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox7[this.calendar1]));
			w8.Position = 0;
			w8.Expand = false;
			w8.Fill = false;
			// Container child hbox7.Gtk.Box+BoxChild
			this.calendar2 = new global::Gtk.Calendar();
			this.calendar2.CanFocus = true;
			this.calendar2.Name = "calendar2";
			this.calendar2.DisplayOptions = ((global::Gtk.CalendarDisplayOptions)(35));
			this.hbox7.Add(this.calendar2);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox7[this.calendar2]));
			w9.Position = 1;
			w9.Expand = false;
			w9.Fill = false;
			this.vbox2.Add(this.hbox7);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.hbox7]));
			w10.Position = 4;
			w10.Expand = false;
			w10.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hseparator17 = new global::Gtk.HSeparator();
			this.hseparator17.Name = "hseparator17";
			this.vbox2.Add(this.hseparator17);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.hseparator17]));
			w11.Position = 5;
			w11.Expand = false;
			w11.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.treeview1 = new global::Gtk.TreeView();
			this.treeview1.CanFocus = true;
			this.treeview1.Name = "treeview1";
			this.GtkScrolledWindow.Add(this.treeview1);
			this.vbox2.Add(this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.GtkScrolledWindow]));
			w13.Position = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox5 = new global::Gtk.HBox();
			this.hbox5.Name = "hbox5";
			this.hbox5.Spacing = 6;
			// Container child hbox5.Gtk.Box+BoxChild
			this.bntcan = new global::Gtk.Button();
			this.bntcan.CanFocus = true;
			this.bntcan.Name = "bntcan";
			this.bntcan.UseUnderline = true;
			this.bntcan.Label = global::Mono.Unix.Catalog.GetString("Atras");
			this.hbox5.Add(this.bntcan);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.bntcan]));
			w14.Position = 0;
			// Container child hbox5.Gtk.Box+BoxChild
			this.butsalir = new global::Gtk.Button();
			this.butsalir.CanFocus = true;
			this.butsalir.Name = "butsalir";
			this.butsalir.UseUnderline = true;
			this.butsalir.Label = global::Mono.Unix.Catalog.GetString("Salir");
			this.hbox5.Add(this.butsalir);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.butsalir]));
			w15.Position = 1;
			this.vbox2.Add(this.hbox5);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.hbox5]));
			w16.Position = 7;
			w16.Expand = false;
			w16.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hseparator18 = new global::Gtk.HSeparator();
			this.hseparator18.Name = "hseparator18";
			this.vbox2.Add(this.hseparator18);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.hseparator18]));
			w17.Position = 8;
			w17.Expand = false;
			w17.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox4 = new global::Gtk.HBox();
			this.hbox4.Name = "hbox4";
			this.hbox4.Spacing = 6;
			// Container child hbox4.Gtk.Box+BoxChild
			this.lblfecha = new global::Gtk.Label();
			this.lblfecha.Name = "lblfecha";
			this.lblfecha.Xpad = 69;
			this.lblfecha.Xalign = 0F;
			this.hbox4.Add(this.lblfecha);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.lblfecha]));
			w18.Position = 0;
			// Container child hbox4.Gtk.Box+BoxChild
			this.lblhora = new global::Gtk.Label();
			this.lblhora.HeightRequest = 28;
			this.lblhora.Name = "lblhora";
			this.lblhora.Xpad = 69;
			this.lblhora.Xalign = 1F;
			this.hbox4.Add(this.lblhora);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.lblhora]));
			w19.Position = 1;
			this.vbox2.Add(this.hbox4);
			global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.hbox4]));
			w20.Position = 9;
			w20.Expand = false;
			w20.Fill = false;
			this.Add(this.vbox2);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 505;
			this.DefaultHeight = 482;
			this.Show();
			this.calendar1.DaySelected += new global::System.EventHandler(this.OnCalendar1DaySelected);
			this.calendar2.DaySelected += new global::System.EventHandler(this.OnCalendar2DaySelected);
			this.bntcan.Clicked += new global::System.EventHandler(this.OnBntcanClicked);
			this.butsalir.Clicked += new global::System.EventHandler(this.OnButton5Clicked);
		}
	}
}
