
// This file has been generated by the GUI designer. Do not modify.
namespace ProYectoX
{
	public partial class Masopciones
	{
		private global::Gtk.VBox vbox10;

		private global::Gtk.Label lblmasopc;

		private global::Gtk.HBox hbox13;

		private global::Gtk.Button btnmodificar;

		private global::Gtk.Button btneliminar;

		private global::Gtk.Button btnreactivar;

		private global::Gtk.HBox hbox14;

		private global::Gtk.Button btnsalirmasopc;

		private global::Gtk.Button btncancelarmasopc;

		private global::Gtk.HBox hbox15;

		private global::Gtk.DrawingArea drawingarea15;

		private global::Gtk.Label lblfechamasopc;

		private global::Gtk.Label lblhoramasopc;

		private global::Gtk.DrawingArea drawingarea14;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget ProYectoX.Masopciones
			this.Name = "ProYectoX.Masopciones";
			this.Title = global::Mono.Unix.Catalog.GetString("Masopciones");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child ProYectoX.Masopciones.Gtk.Container+ContainerChild
			this.vbox10 = new global::Gtk.VBox();
			this.vbox10.Name = "vbox10";
			this.vbox10.Spacing = 6;
			// Container child vbox10.Gtk.Box+BoxChild
			this.lblmasopc = new global::Gtk.Label();
			this.lblmasopc.Name = "lblmasopc";
			this.lblmasopc.LabelProp = global::Mono.Unix.Catalog.GetString("Seleccione una opcion");
			this.vbox10.Add(this.lblmasopc);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox10[this.lblmasopc]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child vbox10.Gtk.Box+BoxChild
			this.hbox13 = new global::Gtk.HBox();
			this.hbox13.Name = "hbox13";
			this.hbox13.Spacing = 6;
			// Container child hbox13.Gtk.Box+BoxChild
			this.btnmodificar = new global::Gtk.Button();
			this.btnmodificar.CanFocus = true;
			this.btnmodificar.Name = "btnmodificar";
			this.btnmodificar.UseUnderline = true;
			this.btnmodificar.Label = global::Mono.Unix.Catalog.GetString("Modificar");
			this.hbox13.Add(this.btnmodificar);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox13[this.btnmodificar]));
			w2.Position = 0;
			// Container child hbox13.Gtk.Box+BoxChild
			this.btneliminar = new global::Gtk.Button();
			this.btneliminar.CanFocus = true;
			this.btneliminar.Name = "btneliminar";
			this.btneliminar.UseUnderline = true;
			this.btneliminar.Label = global::Mono.Unix.Catalog.GetString("Eliminar");
			this.hbox13.Add(this.btneliminar);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox13[this.btneliminar]));
			w3.Position = 1;
			// Container child hbox13.Gtk.Box+BoxChild
			this.btnreactivar = new global::Gtk.Button();
			this.btnreactivar.CanFocus = true;
			this.btnreactivar.Name = "btnreactivar";
			this.btnreactivar.UseUnderline = true;
			this.btnreactivar.Label = global::Mono.Unix.Catalog.GetString("Reactivar");
			this.hbox13.Add(this.btnreactivar);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox13[this.btnreactivar]));
			w4.Position = 2;
			this.vbox10.Add(this.hbox13);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox10[this.hbox13]));
			w5.Position = 1;
			w5.Expand = false;
			w5.Fill = false;
			// Container child vbox10.Gtk.Box+BoxChild
			this.hbox14 = new global::Gtk.HBox();
			this.hbox14.Name = "hbox14";
			this.hbox14.Spacing = 6;
			// Container child hbox14.Gtk.Box+BoxChild
			this.btnsalirmasopc = new global::Gtk.Button();
			this.btnsalirmasopc.CanFocus = true;
			this.btnsalirmasopc.Name = "btnsalirmasopc";
			this.btnsalirmasopc.UseUnderline = true;
			this.btnsalirmasopc.Label = global::Mono.Unix.Catalog.GetString("Salir");
			this.hbox14.Add(this.btnsalirmasopc);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox14[this.btnsalirmasopc]));
			w6.Position = 0;
			// Container child hbox14.Gtk.Box+BoxChild
			this.btncancelarmasopc = new global::Gtk.Button();
			this.btncancelarmasopc.CanFocus = true;
			this.btncancelarmasopc.Name = "btncancelarmasopc";
			this.btncancelarmasopc.UseUnderline = true;
			this.btncancelarmasopc.Label = global::Mono.Unix.Catalog.GetString("Cancelar");
			this.hbox14.Add(this.btncancelarmasopc);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox14[this.btncancelarmasopc]));
			w7.Position = 1;
			this.vbox10.Add(this.hbox14);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox10[this.hbox14]));
			w8.Position = 2;
			w8.Expand = false;
			w8.Fill = false;
			// Container child vbox10.Gtk.Box+BoxChild
			this.hbox15 = new global::Gtk.HBox();
			this.hbox15.Name = "hbox15";
			this.hbox15.Spacing = 6;
			// Container child hbox15.Gtk.Box+BoxChild
			this.drawingarea15 = new global::Gtk.DrawingArea();
			this.drawingarea15.Name = "drawingarea15";
			this.hbox15.Add(this.drawingarea15);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox15[this.drawingarea15]));
			w9.Position = 0;
			// Container child hbox15.Gtk.Box+BoxChild
			this.lblfechamasopc = new global::Gtk.Label();
			this.lblfechamasopc.Name = "lblfechamasopc";
			this.lblfechamasopc.LabelProp = global::Mono.Unix.Catalog.GetString("        ");
			this.hbox15.Add(this.lblfechamasopc);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox15[this.lblfechamasopc]));
			w10.Position = 1;
			w10.Expand = false;
			w10.Fill = false;
			// Container child hbox15.Gtk.Box+BoxChild
			this.lblhoramasopc = new global::Gtk.Label();
			this.lblhoramasopc.Name = "lblhoramasopc";
			this.lblhoramasopc.LabelProp = global::Mono.Unix.Catalog.GetString("        ");
			this.hbox15.Add(this.lblhoramasopc);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox15[this.lblhoramasopc]));
			w11.Position = 2;
			w11.Expand = false;
			w11.Fill = false;
			// Container child hbox15.Gtk.Box+BoxChild
			this.drawingarea14 = new global::Gtk.DrawingArea();
			this.drawingarea14.Name = "drawingarea14";
			this.hbox15.Add(this.drawingarea14);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox15[this.drawingarea14]));
			w12.Position = 3;
			this.vbox10.Add(this.hbox15);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vbox10[this.hbox15]));
			w13.Position = 3;
			w13.Expand = false;
			w13.Fill = false;
			this.Add(this.vbox10);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 534;
			this.DefaultHeight = 122;
			this.Show();
			this.btnsalirmasopc.Clicked += new global::System.EventHandler(this.OnBtnsalirmasopcClicked);
			this.btncancelarmasopc.Clicked += new global::System.EventHandler(this.OnBtncancelarmasopcClicked);
		}
	}
}
