
// This file has been generated by the GUI designer. Do not modify.
namespace ProYectoX
{
	public partial class ReporteGrupos
	{
		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget ProYectoX.ReporteGrupos
			this.Name = "ProYectoX.ReporteGrupos";
			this.Title = global::Mono.Unix.Catalog.GetString("ReporteGrupos");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show();
		}
	}
}
