
// This file has been generated by the GUI designer. Do not modify.
namespace ProYectoX
{
	public partial class ActualizarUsuario
	{
		private global::Gtk.VBox vbox2;

		private global::Gtk.Label lblusuarioactualizar;

		private global::Gtk.VBox vbox4;

		private global::Gtk.HBox hbox6;

		private global::Gtk.Label lblnombreusuario;

		private global::Gtk.Entry entnombreusuario;

		private global::Gtk.HBox hbox7;

		private global::Gtk.Label lblcontrasena;

		private global::Gtk.Entry entry3;

		private global::Gtk.VBox vbox3;

		private global::Gtk.HBox hbox8;

		private global::Gtk.Label lbltipousuario;

		private global::Gtk.ComboBox combobox1;

		private global::Gtk.HBox hbox9;

		private global::Gtk.Button btnguardar;

		private global::Gtk.Button btncancelaractusu;

		private global::Gtk.HBox hbox10;

		private global::Gtk.Label lblfecha;

		private global::Gtk.Label lblhora;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget ProYectoX.ActualizarUsuario
			this.Name = "ProYectoX.ActualizarUsuario";
			this.Title = global::Mono.Unix.Catalog.GetString("ActualizarUsuario");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child ProYectoX.ActualizarUsuario.Gtk.Container+ContainerChild
			this.vbox2 = new global::Gtk.VBox();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.lblusuarioactualizar = new global::Gtk.Label();
			this.lblusuarioactualizar.Name = "lblusuarioactualizar";
			this.lblusuarioactualizar.LabelProp = global::Mono.Unix.Catalog.GetString("Archivo de usuarios");
			this.vbox2.Add(this.lblusuarioactualizar);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.lblusuarioactualizar]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.vbox4 = new global::Gtk.VBox();
			this.vbox4.Name = "vbox4";
			this.vbox4.Spacing = 6;
			// Container child vbox4.Gtk.Box+BoxChild
			this.hbox6 = new global::Gtk.HBox();
			this.hbox6.Name = "hbox6";
			this.hbox6.Spacing = 6;
			// Container child hbox6.Gtk.Box+BoxChild
			this.lblnombreusuario = new global::Gtk.Label();
			this.lblnombreusuario.Name = "lblnombreusuario";
			this.lblnombreusuario.LabelProp = global::Mono.Unix.Catalog.GetString("Nombre de usuario");
			this.hbox6.Add(this.lblnombreusuario);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox6[this.lblnombreusuario]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child hbox6.Gtk.Box+BoxChild
			this.entnombreusuario = new global::Gtk.Entry();
			this.entnombreusuario.CanFocus = true;
			this.entnombreusuario.Name = "entnombreusuario";
			this.entnombreusuario.IsEditable = true;
			this.entnombreusuario.InvisibleChar = '●';
			this.hbox6.Add(this.entnombreusuario);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox6[this.entnombreusuario]));
			w3.Position = 1;
			w3.Expand = false;
			this.vbox4.Add(this.hbox6);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.hbox6]));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.hbox7 = new global::Gtk.HBox();
			this.hbox7.Name = "hbox7";
			this.hbox7.Spacing = 6;
			// Container child hbox7.Gtk.Box+BoxChild
			this.lblcontrasena = new global::Gtk.Label();
			this.lblcontrasena.Name = "lblcontrasena";
			this.lblcontrasena.LabelProp = global::Mono.Unix.Catalog.GetString("Contraseña");
			this.hbox7.Add(this.lblcontrasena);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox7[this.lblcontrasena]));
			w5.Position = 0;
			w5.Expand = false;
			w5.Fill = false;
			// Container child hbox7.Gtk.Box+BoxChild
			this.entry3 = new global::Gtk.Entry();
			this.entry3.CanFocus = true;
			this.entry3.Name = "entry3";
			this.entry3.IsEditable = true;
			this.entry3.InvisibleChar = '●';
			this.hbox7.Add(this.entry3);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox7[this.entry3]));
			w6.Position = 1;
			w6.Expand = false;
			this.vbox4.Add(this.hbox7);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.hbox7]));
			w7.Position = 1;
			w7.Expand = false;
			w7.Fill = false;
			this.vbox2.Add(this.vbox4);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.vbox4]));
			w8.Position = 1;
			w8.Expand = false;
			w8.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.vbox3 = new global::Gtk.VBox();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hbox8 = new global::Gtk.HBox();
			this.hbox8.Name = "hbox8";
			this.hbox8.Spacing = 6;
			// Container child hbox8.Gtk.Box+BoxChild
			this.lbltipousuario = new global::Gtk.Label();
			this.lbltipousuario.Name = "lbltipousuario";
			this.lbltipousuario.LabelProp = global::Mono.Unix.Catalog.GetString("Tipo de usuario");
			this.hbox8.Add(this.lbltipousuario);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox8[this.lbltipousuario]));
			w9.Position = 0;
			w9.Expand = false;
			w9.Fill = false;
			// Container child hbox8.Gtk.Box+BoxChild
			this.combobox1 = global::Gtk.ComboBox.NewText();
			this.combobox1.Name = "combobox1";
			this.hbox8.Add(this.combobox1);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox8[this.combobox1]));
			w10.Position = 1;
			w10.Expand = false;
			w10.Fill = false;
			this.vbox3.Add(this.hbox8);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.hbox8]));
			w11.Position = 0;
			w11.Expand = false;
			w11.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hbox9 = new global::Gtk.HBox();
			this.hbox9.Name = "hbox9";
			this.hbox9.Spacing = 6;
			// Container child hbox9.Gtk.Box+BoxChild
			this.btnguardar = new global::Gtk.Button();
			this.btnguardar.CanFocus = true;
			this.btnguardar.Name = "btnguardar";
			this.btnguardar.UseUnderline = true;
			this.btnguardar.Label = global::Mono.Unix.Catalog.GetString("Guardar");
			this.hbox9.Add(this.btnguardar);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox9[this.btnguardar]));
			w12.Position = 0;
			// Container child hbox9.Gtk.Box+BoxChild
			this.btncancelaractusu = new global::Gtk.Button();
			this.btncancelaractusu.CanFocus = true;
			this.btncancelaractusu.Name = "btncancelaractusu";
			this.btncancelaractusu.UseUnderline = true;
			this.btncancelaractusu.Label = global::Mono.Unix.Catalog.GetString("Cancelar");
			this.hbox9.Add(this.btncancelaractusu);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox9[this.btncancelaractusu]));
			w13.Position = 1;
			this.vbox3.Add(this.hbox9);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.hbox9]));
			w14.Position = 1;
			w14.Expand = false;
			w14.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hbox10 = new global::Gtk.HBox();
			this.hbox10.Name = "hbox10";
			this.hbox10.Spacing = 6;
			// Container child hbox10.Gtk.Box+BoxChild
			this.lblfecha = new global::Gtk.Label();
			this.lblfecha.Name = "lblfecha";
			this.lblfecha.Xpad = 96;
			this.lblfecha.Ypad = 2;
			this.lblfecha.Xalign = 0F;
			this.lblfecha.Yalign = 0F;
			this.hbox10.Add(this.lblfecha);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.hbox10[this.lblfecha]));
			w15.Position = 0;
			// Container child hbox10.Gtk.Box+BoxChild
			this.lblhora = new global::Gtk.Label();
			this.lblhora.Name = "lblhora";
			this.lblhora.Xpad = 87;
			this.lblhora.Ypad = 2;
			this.lblhora.Xalign = 1F;
			this.lblhora.Yalign = 0F;
			this.hbox10.Add(this.lblhora);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.hbox10[this.lblhora]));
			w16.Position = 1;
			this.vbox3.Add(this.hbox10);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.hbox10]));
			w17.Position = 2;
			w17.Expand = false;
			w17.Fill = false;
			this.vbox2.Add(this.vbox3);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.vbox3]));
			w18.Position = 2;
			w18.Expand = false;
			w18.Fill = false;
			this.Add(this.vbox2);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 523;
			this.DefaultHeight = 209;
			this.Show();
			this.btnguardar.Clicked += new global::System.EventHandler(this.OnBtnguardarClicked);
			this.btncancelaractusu.Clicked += new global::System.EventHandler(this.OnBtncancelaractusuClicked);
		}
	}
}
